<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Xiwei Fu" />

<meta name="date" content="2025-12-06" />

<title>prediction_original</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">CLIMASCOPE</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="meteor.html">Proposal</a>
</li>
<li>
  <a href="Introduction.html">Introduction</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    EDA
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="EDA.html">Main Predictors</a>
    </li>
    <li>
      <a href="https://xucy2347.shinyapps.io/NYmeteor_dashboard/">Data Presentation</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Analysis
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="cluster.html">K-means clustering and PCA</a>
    </li>
    <li>
      <a href="prediction.html">Prediction</a>
    </li>
  </ul>
</li>
<li>
  <a href="discussion.html">Discussion</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="screencast.html">
    <span class="fa fa-play-circle"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/jt4977/meteor.github.io.git">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">prediction_original</h1>
<h4 class="author">Xiwei Fu</h4>
<h4 class="date">2025-12-06</h4>

</div>


<pre class="r"><code>library(readr)
library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(lubridate)</code></pre>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     date, intersect, setdiff, union</code></pre>
<pre class="r"><code>library(forecast)</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;quantmod&#39;:
##   method            from
##   as.zoo.data.frame zoo</code></pre>
<pre class="r"><code>library(tidyr)
library(ggplot2)
library(tibble)
library(knitr)
library(forecast)
library(lubridate)
library(xgboost)</code></pre>
<pre><code>## Warning: package &#39;xgboost&#39; was built under R version 4.5.2</code></pre>
<pre class="r"><code>library(stats)
library(grid) </code></pre>
<div id="model-1" class="section level2">
<h2>Model 1</h2>
<div id="data-preparation" class="section level3">
<h3>Data preparation</h3>
<p>In this section we aggregate station‐level meteorological data to the
New York State level and create lagged covariates that will be used as
external regressors in the ARIMAX model.</p>
<pre class="r"><code>data_raw &lt;- read_csv(&quot;df_gen/data/meteor_2016to20_NY.csv&quot;)</code></pre>
<pre><code>## Rows: 113274 Columns: 13
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl  (12): county, fips, sph, vpd, tmmn, tmmx, pr, rmin, rmax, srad, vs, th
## dttm  (1): date
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>dat &lt;- data_raw |&gt;
  mutate(
    tmmx = tmmx - 273.15,
    tmmn = tmmn - 273.15,
    year   = year(date),
    month  = month(date)
  )
dat_state &lt;- dat %&gt;%
group_by(date) %&gt;%
summarise(
tmmx = mean(tmmx, na.rm = TRUE),
sph  = mean(sph,  na.rm = TRUE),
vpd  = mean(vpd,  na.rm = TRUE),
srad = mean(srad, na.rm = TRUE),
vs   = mean(vs,   na.rm = TRUE)
) %&gt;%
arrange(date)

dat_state_lag &lt;- dat_state %&gt;%
mutate(
sph_lag1  = dplyr::lag(sph,  1),
vpd_lag1  = dplyr::lag(vpd,  1),
srad_lag1 = dplyr::lag(srad, 1),
vs_lag1   = dplyr::lag(vs,   1)
) %&gt;%
tidyr::drop_na()

start_year &lt;- year(min(dat_state_lag$date))
start_doy  &lt;- yday(min(dat_state_lag$date))

tmmx_ts &lt;- ts(
dat_state_lag$tmmx,
start     = c(start_year, start_doy),
frequency = 365
)</code></pre>
</div>
<div id="arimax-fourier-model" class="section level3">
<h3>ARIMAX + Fourier model</h3>
<p>To represent strong annual seasonality, we use Fourier terms instead
of a seasonal ARIMA structure. These Fourier harmonics, together with
lagged meteorological covariates, enter the model as external
regressors, while the error term follows a non-seasonal ARIMA process
selected by auto.arima().</p>
<pre class="r"><code>K &lt;- 3
fourier_terms &lt;- fourier(tmmx_ts, K = K)
xreg &lt;- cbind(
fourier_terms,
sph_lag1  = dat_state_lag$sph_lag1,
vpd_lag1  = dat_state_lag$vpd_lag1,
srad_lag1 = dat_state_lag$srad_lag1,
vs_lag1   = dat_state_lag$vs_lag1
)

fit_arimax_fourier &lt;- auto.arima(
tmmx_ts,
xreg     = xreg,
seasonal = FALSE
)
model_info &lt;- tibble(
  Metric = c(&quot;Log-Likelihood&quot;, &quot;Sigma^2&quot;, &quot;AIC&quot;, &quot;AICc&quot;, &quot;BIC&quot;),
  Value = c(
    as.numeric(logLik(fit_arimax_fourier)),
    fit_arimax_fourier$sigma2,
    fit_arimax_fourier$aic,
    fit_arimax_fourier$aicc,
    fit_arimax_fourier$bic
  )
)

kable(
model_info,
digits = 4,
caption = &quot;Overall fit statistics for the ARIMAX + Fourier model&quot;
)</code></pre>
<table>
<caption>Overall fit statistics for the ARIMAX + Fourier model</caption>
<thead>
<tr class="header">
<th align="left">Metric</th>
<th align="right">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Log-Likelihood</td>
<td align="right">-4819.6440</td>
</tr>
<tr class="even">
<td align="left">Sigma^2</td>
<td align="right">11.5696</td>
</tr>
<tr class="odd">
<td align="left">AIC</td>
<td align="right">9669.2880</td>
</tr>
<tr class="even">
<td align="left">AICc</td>
<td align="right">9669.5532</td>
</tr>
<tr class="odd">
<td align="left">BIC</td>
<td align="right">9751.9363</td>
</tr>
</tbody>
</table>
<p>In this specification, the ARIMA component captures short-term
temporal dependence, while Fourier terms describe the smooth annual
cycle. Lagged humidity, vapor-pressure deficit, solar radiation, and
wind speed account for additional meteorological drivers of
temperature.</p>
</div>
<div id="coefficient-summary" class="section level3">
<h3>Coefficient summary</h3>
<p>We present the estimated coefficients and standard errors for the AR
terms, meteorological covariates, and Fourier harmonics.</p>
<pre class="r"><code>coef_est &lt;- coef(fit_arimax_fourier)
se_est   &lt;- sqrt(diag(vcov(fit_arimax_fourier)))

coef_tbl &lt;- tibble(
Term     = names(coef_est),
Estimate = as.numeric(coef_est),
SE       = as.numeric(se_est)
)

kable(
coef_tbl,
digits = 4,
caption = &quot;Coefficient estimates for ARIMAX + Fourier model&quot;
)</code></pre>
<table>
<caption>Coefficient estimates for ARIMAX + Fourier model</caption>
<thead>
<tr class="header">
<th align="left">Term</th>
<th align="right">Estimate</th>
<th align="right">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ar1</td>
<td align="right">0.7726</td>
<td align="right">0.0410</td>
</tr>
<tr class="even">
<td align="left">ar2</td>
<td align="right">-0.2497</td>
<td align="right">0.0375</td>
</tr>
<tr class="odd">
<td align="left">ar3</td>
<td align="right">0.1078</td>
<td align="right">0.0241</td>
</tr>
<tr class="even">
<td align="left">intercept</td>
<td align="right">16.4607</td>
<td align="right">0.9516</td>
</tr>
<tr class="odd">
<td align="left">S1-365</td>
<td align="right">-4.5286</td>
<td align="right">0.3896</td>
</tr>
<tr class="even">
<td align="left">C1-365</td>
<td align="right">-12.3698</td>
<td align="right">0.7226</td>
</tr>
<tr class="odd">
<td align="left">S2-365</td>
<td align="right">0.5384</td>
<td align="right">0.3231</td>
</tr>
<tr class="even">
<td align="left">C2-365</td>
<td align="right">-0.4380</td>
<td align="right">0.3095</td>
</tr>
<tr class="odd">
<td align="left">S3-365</td>
<td align="right">0.5627</td>
<td align="right">0.3020</td>
</tr>
<tr class="even">
<td align="left">C3-365</td>
<td align="right">-0.3102</td>
<td align="right">0.3016</td>
</tr>
<tr class="odd">
<td align="left">sph_lag1</td>
<td align="right">-47.3621</td>
<td align="right">101.2496</td>
</tr>
<tr class="even">
<td align="left">vpd_lag1</td>
<td align="right">0.1925</td>
<td align="right">0.5844</td>
</tr>
<tr class="odd">
<td align="left">srad_lag1</td>
<td align="right">0.0015</td>
<td align="right">0.0023</td>
</tr>
<tr class="even">
<td align="left">vs_lag1</td>
<td align="right">-0.4976</td>
<td align="right">0.0547</td>
</tr>
</tbody>
</table>
</div>
<div id="model-diagnostics" class="section level3">
<h3>Model Diagnostics</h3>
<p>We assess model adequacy by examining residuals. Ideally, residuals
should behave like uncorrelated noise with no systematic temporal
pattern.
<img src="prediction_original_files/figure-html/ljung-table-1.png" width="672" /></p>
<table>
<caption>Ljung–Box Test for ARIMAX + Fourier Residuals</caption>
<thead>
<tr class="header">
<th align="right">Statistic</th>
<th align="right">Degrees.of.freedom</th>
<th align="right">P.value</th>
<th align="right">Model.df</th>
<th align="right">Total.lags.used</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">330.1</td>
<td align="right">362</td>
<td align="right">0.8844</td>
<td align="right">3</td>
<td align="right">365</td>
</tr>
</tbody>
</table>
<p>The residual time series shows no obvious structure, the
autocorrelation function remains within the 95% bounds at most lags, and
the Ljung–Box test is non-significant. Together, these diagnostics
suggest that the ARIMAX + Fourier model has captured most of the
temporal dependence and seasonal pattern in the data, and the remaining
residuals are approximately white noise.</p>
</div>
<div id="forecasting-and-interpretation" class="section level3">
<h3>Forecasting and Interpretation</h3>
<p>We generate multi-step-ahead forecasts using the fitted ARIMAX +
Fourier model. Future Fourier terms are constructed analytically, and
recent lagged covariates are used to build the regressor matrix for the
forecast horizon.</p>
<pre class="r"><code>h &lt;- 730
fourier_future &lt;- fourier(tmmx_ts, K = K, h = h)

recent_block &lt;- dat_state_lag %&gt;%
slice_tail(n = 365)

xreg_future &lt;- cbind(
fourier_future,
sph_lag1  = recent_block$sph_lag1,
vpd_lag1  = recent_block$vpd_lag1,
srad_lag1 = recent_block$srad_lag1,
vs_lag1   = recent_block$vs_lag1
)

fc &lt;- forecast(fit_arimax_fourier, xreg = xreg_future, h = h)

autoplot(fc) +
ggtitle(&quot;Two-Year ARIMAX + Fourier Forecast for Daily Maximum Temperature&quot;) +
xlab(&quot;Time&quot;) +
ylab(&quot;tmmx&quot;)</code></pre>
<p><img src="prediction_original_files/figure-html/unnamed-chunk-5-1.png" width="672" />
The figure presents a two-year forecast of daily maximum temperature
derived from an ARIMAX model augmented with Fourier seasonal terms. The
historical portion of the time series (black) exhibits strong annual
cycles and substantial short-term variability, both of which are
captured by the model. The forecasted values (blue) follow a smooth,
periodic pattern consistent with the dominant seasonal structure. The
incorporation of Fourier harmonics allows the model to represent complex
seasonal behavior more flexibly than classical seasonal ARIMA, resulting
in coherent long-range forecasts that align with the historical
climatological patterns.</p>
</div>
</div>
<div id="model-2" class="section level2">
<h2>Model 2</h2>
<div id="data-preparation-1" class="section level3">
<h3>Data Preparation</h3>
<p>Daily statewide averages for all available meteorological variables
were computed. Feature engineering included lag terms, rolling means,
and time-based indicators (day of year, weekday, year), which help
XGBoost capture temporal dependencies and short-term memory effects.</p>
<pre class="r"><code>dat &lt;- dat %&gt;%
mutate(date = as.Date(date))

dat_state &lt;- dat %&gt;%
group_by(date) %&gt;%
summarise(
tmmx = mean(tmmx, na.rm = TRUE),
tmmn = mean(tmmn, na.rm = TRUE),
sph  = mean(sph,  na.rm = TRUE),
vpd  = mean(vpd,  na.rm = TRUE),
pr   = mean(pr,   na.rm = TRUE),
rmin = mean(rmin, na.rm = TRUE),
rmax = mean(rmax, na.rm = TRUE),
srad = mean(srad, na.rm = TRUE),
vs   = mean(vs,   na.rm = TRUE),
th   = mean(th,   na.rm = TRUE)
) %&gt;%
ungroup() %&gt;%
arrange(date)


dat_ml &lt;- dat_state %&gt;%
mutate(
doy = yday(date),
dow = wday(date, week_start = 1),
year = year(date),
tmmx_lag1 = lag(tmmx, 1),
tmmx_lag2 = lag(tmmx, 2),
tmmx_lag7 = lag(tmmx, 7),
tmmn_lag1 = lag(tmmn, 1),
sph_lag1  = lag(sph, 1),
vpd_lag1  = lag(vpd, 1),
pr_lag1   = lag(pr, 1),
rmin_lag1 = lag(rmin, 1),
rmax_lag1 = lag(rmax, 1),
srad_lag1 = lag(srad, 1),
vs_lag1   = lag(vs, 1)
)

dat_ml$tmmx_roll7 &lt;- as.numeric(stats::filter(dat_ml$tmmx, rep(1/7, 7), sides = 1))

dat_ml &lt;- dat_ml %&gt;% drop_na()</code></pre>
</div>
<div id="xgboost-model" class="section level3">
<h3>XGBoost Model</h3>
<p>The dataset was split chronologically (80% training, 20% testing). An
XGBoost regression model was trained using RMSE as the optimization
metric and early stopping to prevent overfitting.</p>
<pre class="r"><code>split_date &lt;- dat_ml$date[floor(nrow(dat_ml) * 0.8)]
train_df   &lt;- dat_ml %&gt;% filter(date &lt;= split_date)
test_df    &lt;- dat_ml %&gt;% filter(date &gt;  split_date)

feature_cols &lt;- c(
  &quot;tmmn&quot;,&quot;sph&quot;,&quot;vpd&quot;,&quot;pr&quot;,&quot;rmin&quot;,&quot;rmax&quot;,&quot;srad&quot;,&quot;vs&quot;,&quot;th&quot;,
  &quot;tmmx_lag1&quot;,&quot;tmmx_lag2&quot;,&quot;tmmx_lag7&quot;,
  &quot;tmmn_lag1&quot;,&quot;sph_lag1&quot;,&quot;vpd_lag1&quot;,&quot;pr_lag1&quot;,
  &quot;rmin_lag1&quot;,&quot;rmax_lag1&quot;,&quot;srad_lag1&quot;,&quot;vs_lag1&quot;,
  &quot;tmmx_roll7&quot;,&quot;doy&quot;,&quot;dow&quot;,&quot;year&quot;
)

train_x &lt;- as.matrix(train_df[, feature_cols])
train_y &lt;- train_df$tmmx

test_x  &lt;- as.matrix(test_df[, feature_cols])
test_y  &lt;- test_df$tmmx

dtrain &lt;- xgb.DMatrix(train_x, label = train_y)
dtest  &lt;- xgb.DMatrix(test_x,  label = test_y)

params &lt;- list(
  objective        = &quot;reg:squarederror&quot;,
  eval_metric      = &quot;rmse&quot;,
  max_depth        = 5,
  eta              = 0.05,
  subsample        = 0.8,
  colsample_bytree = 0.8
)

set.seed(2025)
xgb_model &lt;- xgb.train(
  params                = params,
  data                  = dtrain,
  nrounds               = 1500,
  evals                 = list(train = dtrain, eval = dtest),
  early_stopping_rounds = 50,
  verbose               = 0   
)

test_pred &lt;- predict(xgb_model, dtest)

test_df &lt;- test_df %&gt;%
  mutate(
    pred  = test_pred,
    resid = tmmx - pred
  )

rmse &lt;- sqrt(mean((test_df$pred - test_df$tmmx)^2))
mae  &lt;- mean(abs(test_df$pred - test_df$tmmx))
mape &lt;- mean(abs((test_df$pred - test_df$tmmx) / test_df$tmmx)) * 100
ss_res &lt;- sum((test_df$tmmx - test_df$pred)^2)
ss_tot &lt;- sum((test_df$tmmx - mean(test_df$tmmx))^2)
r2   &lt;- 1 - ss_res / ss_tot

perf_xgb &lt;- tibble::tibble(
  Metric = c(&quot;RMSE&quot;, &quot;MAE&quot;, &quot;MAPE (%)&quot;, &quot;R²&quot;),
  Value  = c(rmse, mae, mape, r2)
)

knitr::kable(perf_xgb, digits=3, caption=&quot;XGBoost Model Performance (Test Set)&quot;)</code></pre>
<table>
<caption>XGBoost Model Performance (Test Set)</caption>
<thead>
<tr class="header">
<th align="left">Metric</th>
<th align="right">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">RMSE</td>
<td align="right">0.574</td>
</tr>
<tr class="even">
<td align="left">MAE</td>
<td align="right">0.435</td>
</tr>
<tr class="odd">
<td align="left">MAPE (%)</td>
<td align="right">112.168</td>
</tr>
<tr class="even">
<td align="left">R²</td>
<td align="right">0.997</td>
</tr>
</tbody>
</table>
</div>
<div id="model-diagnostics-1" class="section level3">
<h3>Model Diagnostics</h3>
<p>Residual analysis evaluates whether the model captures structure
adequately and whether remaining errors behave randomly.</p>
<pre class="r"><code>p2 &lt;- ggplot(test_df, aes(x = date)) +
  geom_line(aes(y = tmmx,  color = &quot;Observed&quot;), linewidth = 0.7) +
  geom_line(aes(y = pred,  color = &quot;Predicted&quot;), linewidth = 0.7) +
  scale_color_manual(values = c(&quot;Observed&quot; = &quot;black&quot;, &quot;Predicted&quot; = &quot;blue&quot;)) +
  labs(title = &quot;Observed vs Predicted (Test Set)&quot;,
       x = &quot;Date&quot;, y = &quot;tmmx&quot;) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        legend.position = &quot;bottom&quot;)

p3 &lt;- ggplot(test_df, aes(x = date, y = resid)) +
  geom_line() +
  labs(title = &quot;Residuals Over Time&quot;,
       x = &quot;Date&quot;, y = &quot;Residual&quot;) +
  theme_minimal()
acf_obj &lt;- acf(test_df$resid, plot = FALSE)
acf_df  &lt;- with(acf_obj, data.frame(lag = lag, acf = acf))
n       &lt;- length(test_df$resid)
ci      &lt;- 1.96 / sqrt(n)

p5 &lt;- ggplot(acf_df, aes(x = lag, y = acf)) +
  geom_hline(yintercept = 0) +
  geom_segment(aes(xend = lag, yend = 0)) +
  geom_hline(yintercept = c(-ci, ci),
             linetype = &quot;dashed&quot;, colour = &quot;blue&quot;) +
  labs(title = &quot;Residual ACF&quot;, x = &quot;Lag&quot;, y = &quot;ACF&quot;) +
  theme_minimal()

p4 &lt;- ggplot(test_df, aes(x = tmmx, y = pred)) +
  geom_point(alpha = 0.4) +
  geom_abline(slope = 1, intercept = 0,
              colour = &quot;red&quot;, linetype = &quot;dashed&quot;) +
  labs(title = &quot;Predicted vs Observed (Test Set)&quot;,
       x = &quot;Observed tmmx&quot;, y = &quot;Predicted tmmx&quot;) +
  theme_minimal()
p1 &lt;- ggplot(test_df, aes(x = resid)) +
  geom_histogram(bins = 30, colour = &quot;white&quot;, fill = &quot;steelblue&quot;) +
  labs(title = &quot;Residual Distribution (Test Set)&quot;,
       x = &quot;Residual&quot;, y = &quot;Count&quot;) +
  theme_minimal()

multiplot &lt;- function(..., plotlist=NULL, cols=1) {
  library(grid)

  plots &lt;- c(list(...), plotlist)
  numPlots &lt;- length(plots)

  layout &lt;- matrix(seq(1, cols * ceiling(numPlots / cols)),
                   ncol = cols, nrow = ceiling(numPlots / cols))

  grid.newpage()
  pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
  for (i in 1:numPlots) {
    matchidx &lt;- as.data.frame(which(layout == i, arr.ind = TRUE))
    print(plots[[i]], vp = viewport(
      layout.pos.row = matchidx$row,
      layout.pos.col = matchidx$col
    ))
  }
}

multiplot(p1,p2, p3, p4, p5, cols = 2)</code></pre>
<p><img src="prediction_original_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The XGBoost model demonstrates strong predictive performance, with
predicted values closely tracking observed temperatures across the test
period. Residuals are centered around zero with no visible temporal
patterns, and the ACF shows no meaningful autocorrelation, indicating
well-behaved errors. The predicted-versus-observed scatterplot aligns
tightly around the 45-degree line, and the residual distribution is
approximately normal with small variance. Overall, the diagnostics
suggest that XGBoost effectively captures the nonlinear and seasonal
structure of the temperature series and produces accurate, unbiased
predictions.</p>
</div>
<div id="forecasting-and-interpretation-1" class="section level3">
<h3>Forecasting and Interpretation</h3>
<p>Future meteorological covariates were constructed by cycling the most
recent 365-day pattern, enabling the model to simulate realistic
seasonal dynamics.</p>
<pre class="r"><code>dat_state &lt;- dat %&gt;%
  mutate(date = as.Date(date)) %&gt;%
  group_by(date) %&gt;%
  summarise(
    tmmx = mean(tmmx, na.rm = TRUE),
    tmmn = mean(tmmn, na.rm = TRUE),
    sph  = mean(sph,  na.rm = TRUE),
    vpd  = mean(vpd,  na.rm = TRUE),
    pr   = mean(pr,   na.rm = TRUE),
    rmin = mean(rmin, na.rm = TRUE),
    rmax = mean(rmax, na.rm = TRUE),
    srad = mean(srad, na.rm = TRUE),
    vs   = mean(vs,   na.rm = TRUE),
    th   = mean(th,   na.rm = TRUE)
  ) %&gt;%
  ungroup() %&gt;%
  arrange(date)

last_365_block &lt;- dat_state %&gt;%
  slice_tail(n = 365) %&gt;%
  select(tmmn, sph, vpd, pr, rmin, rmax, srad, vs, th)


h &lt;- 730   
future_list &lt;- vector(&quot;list&quot;, length = h)

state &lt;- dat_ml %&gt;%
  arrange(date) %&gt;%
  slice_tail(n = 7)

last_date &lt;- max(state$date)

for (i in seq_len(h)) {

  new_date &lt;- last_date + i
  idx &lt;- ((i - 1) %% 365) + 1
  exo_today &lt;- last_365_block[idx, ]

 
  tmp &lt;- tibble::tibble(
    date = new_date,
    tmmn = exo_today$tmmn,
    sph  = exo_today$sph,
    vpd  = exo_today$vpd,
    pr   = exo_today$pr,
    rmin = exo_today$rmin,
    rmax = exo_today$rmax,
    srad = exo_today$srad,
    vs   = exo_today$vs,
    th   = exo_today$th,
    doy  = yday(new_date),
    dow  = wday(new_date, week_start = 1),
    year = year(new_date)
  )


  tmp &lt;- tmp %&gt;%
    mutate(
      tmmx_lag1  = state$tmmx[nrow(state)],
      tmmx_lag2  = state$tmmx[nrow(state) - 1],
      tmmx_lag7  = state$tmmx[nrow(state) - 6],

      tmmn_lag1  = state$tmmn[nrow(state)],
      sph_lag1   = state$sph[nrow(state)],
      vpd_lag1   = state$vpd[nrow(state)],
      pr_lag1    = state$pr[nrow(state)],
      rmin_lag1  = state$rmin[nrow(state)],
      rmax_lag1  = state$rmax[nrow(state)],
      srad_lag1  = state$srad[nrow(state)],
      vs_lag1    = state$vs[nrow(state)],

  
      tmmx_roll7 = mean(state$tmmx)
    )

  x_new &lt;- as.matrix(tmp[, feature_cols])

  pred_new &lt;- predict(xgb_model, xgb.DMatrix(x_new))

  tmp$tmmx &lt;- as.numeric(pred_new)   

  future_list[[i]] &lt;- tmp

  state &lt;- dplyr::bind_rows(state, tmp)
  state &lt;- state %&gt;% slice_tail(n = 7)
}

future_730 &lt;- dplyr::bind_rows(future_list)

sd_resid &lt;- sd(test_df$resid)

future_730 &lt;- future_730 %&gt;%
  mutate(
    tmmx_pred = tmmx,
    lower_95  = tmmx_pred - 1.96 * sd_resid,
    upper_95  = tmmx_pred + 1.96 * sd_resid
  )

past_all &lt;- dat_state %&gt;%
  arrange(date) %&gt;%
  select(date, tmmx) %&gt;%
  mutate(source = &quot;Observed (all history)&quot;)


future_plot &lt;- future_730 %&gt;%
  select(date, tmmx_pred, lower_95, upper_95) %&gt;%
  mutate(source = &quot;XGBoost forecast&quot;)

ggplot() +
  geom_line(data = past_all,
            aes(x = date, y = tmmx, color = &quot;Observed&quot;),
            linewidth = 0.7) +

  geom_ribbon(data = future_plot,
              aes(x = date, ymin = lower_95, ymax = upper_95, fill = &quot;95% PI&quot;),
              alpha = 0.2, inherit.aes = FALSE) +
  geom_line(data = future_plot,
            aes(x = date, y = tmmx_pred, color = &quot;Forecast&quot;),
            linewidth = 0.7) +
  labs(
    title = &quot;XGBoost forecast of daily max temperature\n(next 730 days with approximate 95% prediction interval)&quot;,
    x = &quot;Date&quot;,
    y = &quot;Max temperature (tmmx, °C)&quot;
  ) +
  scale_color_manual(
    values = c(&quot;Observed&quot; = &quot;black&quot;, &quot;Forecast&quot; = &quot;blue&quot;)
  ) +
  scale_fill_manual(
    values = c(&quot;95% PI&quot; = &quot;red&quot;)
  ) +
  theme_minimal() +
  theme(
    legend.title  = element_blank(),
    plot.title    = element_text(hjust = 0.5)
  )</code></pre>
<p><img src="prediction_original_files/figure-html/unnamed-chunk-9-1.png" width="672" />
This XGBoost model effectively captures nonlinear meteorological and
temporal dependencies, delivering strong short-term predictive accuracy
and stable long-horizon forecasts. The model serves as a complementary
alternative to ARIMAX, offering improved flexibility in handling lagged
covariates and complex interactions.</p>
</div>
</div>
<div id="model-comparison" class="section level2">
<h2>Model Comparison</h2>
<pre class="r"><code>ar_train &lt;- dat_state_lag %&gt;% filter(date &lt;= split_date)
ar_test  &lt;- dat_state_lag %&gt;% filter(date &gt;  split_date)

if (nrow(ar_test) == 0 | nrow(ar_train) == 0) {
  stop(&quot;ARIMAX train/test split produced empty set. Check date ranges of dat_state_lag vs dat_ml.&quot;)
}

start_year &lt;- year(min(ar_train$date))
start_doy  &lt;- yday(min(ar_train$date))

tmmx_ts_train &lt;- ts(
  ar_train$tmmx,
  start     = c(start_year, start_doy),
  frequency = 365
)

K &lt;- 3

fourier_train &lt;- fourier(tmmx_ts_train, K = K)

xreg_train &lt;- cbind(
  fourier_train,
  sph_lag1  = ar_train$sph_lag1,
  vpd_lag1  = ar_train$vpd_lag1,
  srad_lag1 = ar_train$srad_lag1,
  vs_lag1   = ar_train$vs_lag1
)

fit_arimax_cv &lt;- auto.arima(
  tmmx_ts_train,
  xreg     = xreg_train,
  seasonal = FALSE
)


h_test &lt;- nrow(ar_test)

fourier_test &lt;- fourier(tmmx_ts_train, K = K, h = h_test)

xreg_test &lt;- cbind(
  fourier_test,
  sph_lag1  = ar_test$sph_lag1,
  vpd_lag1  = ar_test$vpd_lag1,
  srad_lag1 = ar_test$srad_lag1,
  vs_lag1   = ar_test$vs_lag1
)

fc_test &lt;- forecast(
  fit_arimax_cv,
  xreg = xreg_test,
  h    = h_test
)

ar_test &lt;- ar_test %&gt;%
  mutate(arimax_pred = as.numeric(fc_test$mean))

compare_df &lt;- test_df %&gt;%
  select(date, tmmx, xgb_pred = pred) %&gt;%
  inner_join(ar_test %&gt;% select(date, arimax_pred),
             by = &quot;date&quot;) %&gt;%
  arrange(date)

if (nrow(compare_df) == 0) {
  stop(&quot;No overlapping dates between XGBoost test_df and ARIMAX test set. Check date alignment.&quot;)
}

calc_metrics &lt;- function(obs, pred) {
  rmse &lt;- sqrt(mean((pred - obs)^2))
  mae  &lt;- mean(abs(pred - obs))
  mape &lt;- mean(abs((pred - obs) / obs)) * 100
  ss_res &lt;- sum((obs - pred)^2)
  ss_tot &lt;- sum((obs - mean(obs))^2)
  r2 &lt;- 1 - ss_res / ss_tot
  c(RMSE = rmse, MAE = mae, MAPE = mape, R2 = r2)
}

m_arimax &lt;- calc_metrics(compare_df$tmmx, compare_df$arimax_pred)
m_xgb    &lt;- calc_metrics(compare_df$tmmx, compare_df$xgb_pred)

model_compare &lt;- tibble::tibble(
  Model = c(&quot;ARIMAX + Fourier&quot;, &quot;XGBoost&quot;),
  RMSE  = c(m_arimax[&quot;RMSE&quot;], m_xgb[&quot;RMSE&quot;]),
  MAE   = c(m_arimax[&quot;MAE&quot;],  m_xgb[&quot;MAE&quot;]),
  MAPE  = c(m_arimax[&quot;MAPE&quot;], m_xgb[&quot;MAPE&quot;]),
  R2    = c(m_arimax[&quot;R2&quot;],   m_xgb[&quot;R2&quot;])
)

kable(model_compare, digits = 3,
      caption = &quot;Performance comparison of ARIMAX + Fourier vs XGBoost on the same test dates&quot;)</code></pre>
<table>
<caption>Performance comparison of ARIMAX + Fourier vs XGBoost on the
same test dates</caption>
<thead>
<tr class="header">
<th align="left">Model</th>
<th align="right">RMSE</th>
<th align="right">MAE</th>
<th align="right">MAPE</th>
<th align="right">R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ARIMAX + Fourier</td>
<td align="right">8.593</td>
<td align="right">7.608</td>
<td align="right">1151.313</td>
<td align="right">0.291</td>
</tr>
<tr class="even">
<td align="left">XGBoost</td>
<td align="right">0.574</td>
<td align="right">0.435</td>
<td align="right">112.168</td>
<td align="right">0.997</td>
</tr>
</tbody>
</table>
<p>The test-set results show that XGBoost substantially outperforms the
ARIMAX + Fourier model across all metrics, with far lower RMSE (0.57
vs. 8.59), MAE (0.43 vs. 7.61), and MAPE (112% vs. 1151%), as well as a
much higher R² (0.997 vs. 0.291). These differences are consistent with
the theoretical design of the two models. The ARIMAX + Fourier approach
relies on linear relationships, predefined seasonal components, and a
limited set of lagged regressors; as a result, it struggles to capture
nonlinear temperature dynamics and complex interactions among
meteorological variables. In contrast, XGBoost is a gradient-boosted
ensemble model capable of learning highly flexible, nonlinear
relationships and automatically capturing interactions among features,
including multiple lags, rolling averages, and time-of-year effects.
This flexibility allows it to model temperature patterns far more
accurately. However, ARIMAX has advantages in interpretability and
classical time-series structure, while XGBoost, despite its higher
accuracy, behaves more like a black box and requires more computational
resources. Overall, the comparison suggests that XGBoost is markedly
better suited for predictive performance in this dataset, especially
when nonlinear and interaction effects are important.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
