% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{caption}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{array}
\usepackage{anyfontsize}
\usepackage{multirow}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Report},
  pdfauthor={Anqi Li, Chuyuan Xu, Jingtong He, Kaicheng Mo, Xiwei Fu},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Report}
\author{Anqi Li, Chuyuan Xu, Jingtong He, Kaicheng Mo, Xiwei Fu}
\date{2025-12-06}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{\texorpdfstring{\textbf{Group
Members}}{Group Members}}\label{group-members}

Jingtong He(jh4977), Chuyuan Xu(cx2347), Anqi Li(al4771), Xiwei
Fu(xf2290), Kaicheng Mo(km4071)

\section{\texorpdfstring{\textbf{Project
Title}}{Project Title}}\label{project-title}

ClimaScope: Forecasting the Empire Skies

\section{\texorpdfstring{\textbf{Motivation}}{Motivation}}\label{motivation}

New York State's climate has already warmed substantially, with
increases in mean and extreme temperatures and changes in precipitation
documented over the twentieth and early twenty‑first centuries and
projected to intensify under all plausible emissions scenarios (Lamie et
al., 2024). These shifts amplify risks to human health, infrastructure
and ecosystems, particularly through more frequent heat extremes, heavy
rainfall and flooding, underscoring the need for decision‑relevant
climate information at sub‑state scales (Barnes et al., 2024). While
global classification schemes such as the Köppen--Geiger system provide
a useful first‑order view of climate regimes, they do not resolve
county‑level variation in multivariate weather conditions within a
single state (Peel, Finlayson and McMahon, 2007).

\section{\texorpdfstring{\textbf{Related
Work}}{Related Work}}\label{related-work}

Using 2016--2020 daily county‑level meteorological observations, this
project develops an integrated, three‑part statistical characterisation
of New York's near‑surface climate designed to support downstream impact
analyses.

First, we aggregate daily variables to the state level to describe
seasonal and inter‑annual variability in maximum temperature and related
meteorological quantities.

Second, we construct county‑specific long‑term climate
profiles---summaries of temperature, humidity, precipitation, solar
radiation and wind speed---and apply principal component analysis (PCA)
followed by k-means clustering to identify objectively defined climate
types, following established multivariate climate regionalisation
approaches that combine dimensionality reduction with unsupervised
clustering.

Third, we treat statewide daily maximum temperature as a primary outcome
and develop an ARIMAX model with Fourier seasonal terms and time‑lagged
meteorological covariates (humidity, vapour‑pressure deficit, solar
radiation and wind speed) to capture both the dominant annual cycle and
shorter‑term weather dependencies, building on recommended practice for
ARIMA‑family models with harmonic regressors in environmental
time‑series forecasting (Hyndman and Athanasopoulos, 2018; Bazrafshan et
al., 2025).

The overarching motivation is to obtain interpretable spatial climate
types, a low‑dimensional representation of the main climate gradient
across New York, and a calibrated forecasting model for daily heat at
the state level, thereby generating meteorological inputs that can in
future be coupled to health, infrastructure or ecological outcome models
in support of climate‑resilient planning.

\section{\texorpdfstring{\textbf{Initial
Questions}}{Initial Questions}}\label{initial-questions}

Our initial questions were designed to explore New York State's
multivariate climate patterns and guide the development of a meaningful
statistical characterization.

\begin{itemize}
\item
  How do seasonal and inter-annual variations in key meteorological
  variables manifest across New York State, and what broad climate
  signals can be observed at the state level? As we examined these
  trends, we began to consider whether certain variables contributed
  disproportionately to statewide variability and whether long-term
  warming patterns might shift these signals over time.
\item
  To what extent do counties differ in their long-term climate profiles,
  and can unsupervised methods such as PCA and k-means clustering reveal
  distinct, objectively defined climate types? The PCA results prompted
  new questions about the stability of the extracted gradients, the
  robustness of clusters to alternative variable selections or scaling
  choices, and whether the identified climate types could meaningfully
  support downstream applications such as health or infrastructure risk
  modeling.
\item
  Can a time-series forecasting model effectively capture both the
  dominant annual temperature cycle and shorter-term weather
  dependencies?
\end{itemize}

As we refined the model, additional questions arose regarding the
sensitivity of forecasts to lag structures, the potential value of
additional covariates, and how such forecasts might integrate with the
county-level climate classifications.

\section{\texorpdfstring{\textbf{Data
Summary}}{Data Summary}}\label{data-summary}

\subsection{Dataset}\label{dataset}

The datasets recording various meteorological variables were downloaded
from \textbf{\href{https://doi.org/10.7910/DVN/FYTME3}{``Daily
meteorological Gridmet variables by United States administrative
boundaries'', Harvard Dataverse}}. The dataset provides spatial
aggregations of meteorological for US counties. To monitor the changing
patterns in the past seasons and years, meteorological data from 2016 to
2020 on the county level were downloaded to get the closest observations
available.\\
\strut \\
Key meteorological factors used for visualization and addressing our
research question are:\\
\strut ~~~~\texttt{county}: Federal Information Processing Series
(FIPS), the id of the counties;\\
\strut ~~~~\texttt{date}: date of the estimated meteorological
variables;\\
\strut ~~~~\texttt{sph}: near-surface specific humidity (Mass
fraction);\\
\strut ~~~~\texttt{vpd}: mean vapor pressure deficit (kPa);\\
\strut ~~~~\texttt{tmmn}: minimum near-surface air temperature
(Kelvin);\\
\strut ~~~~\texttt{tmmx}: maximum near-surface air temperature
(Kelvin);\\
\strut ~~~~\texttt{pr}: precipitation (mm, daily total);\\
\strut ~~~~\texttt{rmin}: minimum near-surface relative humidity (\%);\\
\strut ~~~~\texttt{rmax}: maximum near-surface relative humidity (\%);\\
\strut ~~~~\texttt{srad}: surface downwelling solar radiation
(W/m\^{}2);\\
\strut ~~~~\texttt{vs}: wind speed at 10m (m/s);\\
\strut ~~~~\texttt{th}: wind direction at 10m (degree).\\
\strut \\
Corresponding county information was downloaded from
\textbf{\href{https://www.census.gov/cgi-bin/geo/shapefiles/index.php}{tiger/line
Shapefiles}}. Due to the lapse in federal funding, portions of the
\textbf{\href{https://www.census.gov/}{United States Census Bureau}}
were unavailable. \texttt{tl\_2020\_state} and \texttt{tl\_2024\_county}
were downloaded to obtain additional New York state and county
information to facilitate visualizations and analysis.\\
Key variables in \texttt{tl\_2024\_county} include:\\
\strut ~~~~\texttt{GEOID}: Current county identifier; a concatenation of
current state FIPS code and county FIPS code;\\
\strut ~~~~\texttt{STUSPS}: Current United States Postal Service (USPS)
state abbreviation;\\
\strut ~~~~\texttt{NAME}: Current state name;\\
\strut ~~~~\texttt{NAMELSAD}: Current name and the translated LSAD code
for county;\\
\strut ~~~~\texttt{geometry}: the geological boundaries in the geometry
of multipolygon.\\
\strut \\
Key variables in \texttt{tl\_2020\_state} are:\\
\strut ~~~~\texttt{STATEFP}: State FIPS code;\\
\strut ~~~~\texttt{STUSPS}: Current United States Postal Service (USPS)
state abbreviation;\\
\strut ~~~~\texttt{NAME}: Current county name.\\

\subsection{Data Cleaning}\label{data-cleaning}

\subsubsection{Meteorological Factors
dataset}\label{meteorological-factors-dataset}

Due to the fact that each raw dataset exceeds the maximum upload file
size (\textgreater50 MB), data cleaning was performed on a local drive.
The tidied dataset is available on
\href{https://github.com/jt4977/meteor.github.io/tree/main/df_gen}{our
Github}. Meteorological datasets from 2016 to 2020 were combined, and
only counties in the NY states would be selected for the new dataset.
The new dataset has 113274 observations, each with unique dates and FIPs
code, and 6 variables with county information and meteorological
factors. In later analysis, minimum and maximum near-surface air
temperatures were converted from Kelvin into Celsius.\\
\strut \\

\subsubsection{NY County Information}\label{ny-county-information}

All the FIPs in the state of New York were first filtered out from the
dataset on states, and county information was joined to serve as a
supplement of county names and multiploygon geographical information.
The new dataset now includes 62 unique NY counties and 6. Data points
are usually stored in the two sections above and merged when needed.

\section{\texorpdfstring{\textbf{Exploratory Data
Analysis}}{Exploratory Data Analysis}}\label{exploratory-data-analysis}

\subsection{Overview}\label{overview}

This interface presents exploratory summaries of county‑level
meteorological conditions in New York State for the period 2016--2020.
The underlying dataset links daily observations to county polygons via
the FIPS county identifier (\texttt{fips}) and calendar date
(\texttt{date}). Maximum near‑surface air temperature (\texttt{tmmx},
recorded in Kelvin) is converted to degrees Celsius (\texttt{tmmx\_C})
and used to calculate statewide daily means, the annual number of
``hot'' days above 30\,°C, and multi‑year county averages. Daily total
precipitation (\texttt{pr}, in millimetres) is grouped by meteorological
season to characterise the distribution and frequency of wet days, while
vapor pressure deficit (\texttt{vpd}, in kPa) is analysed jointly with
temperature to illustrate how atmospheric dryness changes under
different heat conditions. Derived temporal variables such as
\texttt{month}, \texttt{season}, and \texttt{year} organise the data in
time, and geographic coordinates of county centroids (\texttt{lon},
\texttt{lat}) support the interactive map. Together, these variables
provide a compact description of how temperature, moisture, and heat
extremes vary across space and time in New York State.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\NormalTok{opts\_chunk}\SpecialCharTok{$}\FunctionTok{set}\NormalTok{(}
\AttributeTok{echo =} \ConstantTok{TRUE}\NormalTok{, }
\AttributeTok{warning =} \ConstantTok{FALSE}\NormalTok{,}
\AttributeTok{message =} \ConstantTok{FALSE}
\NormalTok{)}

\FunctionTok{library}\NormalTok{(tidyverse) }
\FunctionTok{library}\NormalTok{(sf) }
\FunctionTok{library}\NormalTok{(readr)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(lubridate)}
\FunctionTok{library}\NormalTok{(leaflet)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{meteor }\OtherTok{\textless{}{-}}\NormalTok{ readr}\SpecialCharTok{::}\FunctionTok{read\_csv}\NormalTok{(}\StringTok{"df\_gen/data/meteor\_2016to20\_NY.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ny\_county }\OtherTok{\textless{}{-}}\NormalTok{ sf}\SpecialCharTok{::}\FunctionTok{st\_read}\NormalTok{(}\StringTok{"df\_gen/data/NYcounty\_fips/NYcounty\_fips.shp"}\NormalTok{,}
  \AttributeTok{quiet =} \ConstantTok{TRUE}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ny\_county }\OtherTok{\textless{}{-}}\NormalTok{ ny\_county }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{fips =} \FunctionTok{as.character}\NormalTok{(fips))}

\NormalTok{meteor }\OtherTok{\textless{}{-}}\NormalTok{ meteor }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{fips =} \FunctionTok{as.character}\NormalTok{(fips))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ny\_meteor\_all }\OtherTok{\textless{}{-}}\NormalTok{ ny\_county }\SpecialCharTok{|\textgreater{}}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{left\_join}\NormalTok{(meteor, }\AttributeTok{by =} \StringTok{"fips"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Daily statewide mean of maximum temperature in New York
(2016--2020)}\label{daily-statewide-mean-of-maximum-temperature-in-new-york-20162020}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{state\_tmmx\_ts }\OtherTok{\textless{}{-}}\NormalTok{ ny\_meteor\_all }\SpecialCharTok{|\textgreater{}}
\NormalTok{  sf}\SpecialCharTok{::}\FunctionTok{st\_drop\_geometry}\NormalTok{() }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(date) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{tmmx\_mean\_K =} \FunctionTok{mean}\NormalTok{(tmmx, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{tmmx\_mean\_C =}\NormalTok{ tmmx\_mean\_K }\SpecialCharTok{{-}} \FloatTok{273.15}\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(state\_tmmx\_ts, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date, }\AttributeTok{y =}\NormalTok{ tmmx\_mean\_C)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.6}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Daily statewide mean of maximum temperature in New York (2016–2020)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Date"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Mean daily maximum temperature (°C)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/fig1-1.pdf}}

The curve shows the mean daily maximum near‑surface air temperature,
averaged across all New York State counties and expressed in degrees
Celsius. The pronounced peaks and troughs illustrate the strong
intra‑annual seasonal cycle, with warm summers and cold winters
repeating over the five‑year period. The series also highlights
shorter‑term variability and occasional extreme hot and cold days
superimposed on this seasonal pattern.

\subsection{Seasonal distribution of daily precipitation across New York
State}\label{seasonal-distribution-of-daily-precipitation-across-new-york-state}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ny\_meteor\_no\_geom }\OtherTok{\textless{}{-}}\NormalTok{ ny\_meteor\_all }\SpecialCharTok{|\textgreater{}}
\NormalTok{  sf}\SpecialCharTok{::}\FunctionTok{st\_drop\_geometry}\NormalTok{()}

\NormalTok{seasonal\_pr }\OtherTok{\textless{}{-}}\NormalTok{ ny\_meteor\_no\_geom }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{month =} \FunctionTok{month}\NormalTok{(date),}
    \AttributeTok{season =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      month }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{12}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \StringTok{"Winter"}\NormalTok{,}
\NormalTok{      month }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{)  }\SpecialCharTok{\textasciitilde{}} \StringTok{"Spring"}\NormalTok{,}
\NormalTok{      month }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{6}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{8}\NormalTok{)  }\SpecialCharTok{\textasciitilde{}} \StringTok{"Summer"}\NormalTok{,}
      \ConstantTok{TRUE}                  \SpecialCharTok{\textasciitilde{}} \StringTok{"Autumn"}
\NormalTok{    )}
\NormalTok{  )}

\FunctionTok{ggplot}\NormalTok{(seasonal\_pr, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ season, }\AttributeTok{y =}\NormalTok{ pr)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{outlier.alpha =} \FloatTok{0.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_sqrt}\NormalTok{(}\AttributeTok{name =} \StringTok{"Daily precipitation (mm, sqrt scale)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Seasonal distribution of daily precipitation across New York State"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Season"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/fig2_seasonal_pr_boxplot-1.pdf}}

Box‑and‑whisker plots summarise the distribution of county‑level daily
total precipitation (mm) for each meteorological season over 2016--2020,
displayed on a square‑root scale to make moderate and heavy rainfall
more visible. All seasons exhibit a highly right‑skewed distribution,
reflecting many days with little or no rain and a smaller number of
intense precipitation events. Differences between seasons suggest modest
shifts in both typical and extreme rainfall amounts across the annual
cycle.

\subsection{Relationship between daily maximum temperature and vapor
pressure
deficit}\label{relationship-between-daily-maximum-temperature-and-vapor-pressure-deficit}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}

\NormalTok{scatter\_dat }\OtherTok{\textless{}{-}}\NormalTok{ ny\_meteor\_no\_geom}\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(fips, date, tmmx, vpd) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(tmmx), }\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(vpd)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{tmmx\_C =}\NormalTok{ tmmx }\SpecialCharTok{{-}} \FloatTok{273.15}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{slice\_sample}\NormalTok{(}\AttributeTok{n =} \DecValTok{5000}\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(scatter\_dat, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ tmmx\_C, }\AttributeTok{y =}\NormalTok{ vpd)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.25}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.6}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"loess"}\NormalTok{, }\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Relationship between daily maximum temperature and vapor pressure deficit"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Daily maximum temperature (°C)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Vapor pressure deficit (kPa)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/fig3_tmmx_vpd_scatter-1.pdf}}

Each grey point represents a sampled county--day pair from 2016--2020,
plotting daily maximum temperature (°C) against the corresponding vapor
pressure deficit (kPa), while the blue line shows a non‑parametric
smooth fitted to the cloud of points. The scatter reveals a strong,
non‑linear positive association, with VPD increasing rapidly at higher
temperatures, consistent with warmer air having a greater capacity for
holding water vapour. This pattern indicates that hot conditions in New
York are typically accompanied by drier atmospheric demand, which is
relevant for both ecological water stress and human heat exposure.

\subsection{Average number of hot days (T\_max ≥ 30 °C) per county by
year}\label{average-number-of-hot-days-t_max-30-c-per-county-by-year}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hot\_threshold\_K }\OtherTok{\textless{}{-}} \DecValTok{30} \SpecialCharTok{+} \FloatTok{273.15}

\NormalTok{yearly\_hot\_days }\OtherTok{\textless{}{-}}\NormalTok{ ny\_meteor\_no\_geom }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{year =} \FunctionTok{year}\NormalTok{(date),}
    \AttributeTok{is\_hot =}\NormalTok{ tmmx }\SpecialCharTok{\textgreater{}=}\NormalTok{ hot\_threshold\_K}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(fips, year) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{hot\_days =} \FunctionTok{sum}\NormalTok{(is\_hot, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(year) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{mean\_hot\_days =} \FunctionTok{mean}\NormalTok{(hot\_days, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\FunctionTok{ggplot}\NormalTok{(yearly\_hot\_days, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{factor}\NormalTok{(year), }\AttributeTok{y =}\NormalTok{ mean\_hot\_days)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Average number of hot days (T\_max ≥ 30 °C) per county by year"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Year"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Mean number of hot days per county"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/fig4_yearly_hot_days-1.pdf}}

Bars display, for each calendar year from 2016 to 2020, the mean number
of days per county on which the daily maximum temperature reached or
exceeded 30 °C. The metric provides a simple indicator of
population‑level exposure to potentially hazardous heat across the
state. The inter‑annual differences in bar height indicate that the
frequency of such hot days varies appreciably from year to year over the
study period.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ny\_meteor\_tbl }\OtherTok{\textless{}{-}}\NormalTok{ ny\_meteor\_all }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{st\_drop\_geometry}\NormalTok{() }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{tmmx\_C =}\NormalTok{ tmmx }\SpecialCharTok{{-}} \FloatTok{273.15}\NormalTok{)}

\NormalTok{county\_mean\_tmmx }\OtherTok{\textless{}{-}}\NormalTok{ ny\_meteor\_tbl }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(fips) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{mean\_tmmx\_C =} \FunctionTok{mean}\NormalTok{(tmmx\_C, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{.groups     =} \StringTok{"drop"}
\NormalTok{  )}

\NormalTok{ny\_county\_centroid }\OtherTok{\textless{}{-}}\NormalTok{ ny\_county }\SpecialCharTok{|\textgreater{}}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(fips, name, geometry) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{st\_transform}\NormalTok{(}\DecValTok{4326}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{centroid =} \FunctionTok{st\_centroid}\NormalTok{(geometry)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{lon =} \FunctionTok{st\_coordinates}\NormalTok{(centroid)[, }\DecValTok{1}\NormalTok{],}
    \AttributeTok{lat =} \FunctionTok{st\_coordinates}\NormalTok{(centroid)[, }\DecValTok{2}\NormalTok{]}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
\NormalTok{  dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{centroid)}

\NormalTok{ny\_map\_data }\OtherTok{\textless{}{-}}\NormalTok{ ny\_county\_centroid }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{left\_join}\NormalTok{(county\_mean\_tmmx, }\AttributeTok{by =} \StringTok{"fips"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Interactive map of mean daily maximum temperature by
county}\label{interactive-map-of-mean-daily-maximum-temperature-by-county}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pal }\OtherTok{\textless{}{-}} \FunctionTok{colorNumeric}\NormalTok{(}
  \AttributeTok{palette =} \StringTok{"YlOrRd"}\NormalTok{,}
  \AttributeTok{domain  =}\NormalTok{ ny\_map\_data}\SpecialCharTok{$}\NormalTok{mean\_tmmx\_C,}
  \AttributeTok{na.color =} \StringTok{"transparent"}
\NormalTok{)}

\FunctionTok{leaflet}\NormalTok{(ny\_map\_data, }\AttributeTok{options =} \FunctionTok{leafletOptions}\NormalTok{(}\AttributeTok{minZoom =} \DecValTok{5}\NormalTok{, }\AttributeTok{maxZoom =} \DecValTok{10}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{addProviderTiles}\NormalTok{(}\StringTok{"CartoDB.Positron"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  
  \FunctionTok{addPolygons}\NormalTok{(}
    \AttributeTok{fillColor   =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{pal}\NormalTok{(mean\_tmmx\_C),}
    \AttributeTok{color       =} \StringTok{"\#555555"}\NormalTok{,}
    \AttributeTok{weight      =} \FloatTok{0.5}\NormalTok{,}
    \AttributeTok{fillOpacity =} \FloatTok{0.7}\NormalTok{,}
    \AttributeTok{smoothFactor =} \FloatTok{0.2}\NormalTok{,}
    \AttributeTok{highlight =} \FunctionTok{highlightOptions}\NormalTok{(}
      \AttributeTok{weight      =} \DecValTok{2}\NormalTok{,}
      \AttributeTok{color       =} \StringTok{"\#000000"}\NormalTok{,}
      \AttributeTok{fillOpacity =} \FloatTok{0.9}\NormalTok{,}
      \AttributeTok{bringToFront =} \ConstantTok{TRUE}
\NormalTok{    ),}
    \AttributeTok{label =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{paste0}\NormalTok{(}
\NormalTok{      name, }\StringTok{" County: "}\NormalTok{,}
      \FunctionTok{round}\NormalTok{(mean\_tmmx\_C, }\DecValTok{1}\NormalTok{), }\StringTok{" °C"}
\NormalTok{    ),}
    \AttributeTok{popup =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{paste0}\NormalTok{(}
      \StringTok{"\textless{}strong\textgreater{}"}\NormalTok{, name, }\StringTok{" County\textless{}/strong\textgreater{}\textless{}br/\textgreater{}"}\NormalTok{,}
      \StringTok{"Mean T\textless{}sub\textgreater{}max\textless{}/sub\textgreater{}: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(mean\_tmmx\_C, }\DecValTok{1}\NormalTok{), }\StringTok{" °C\textless{}br/\textgreater{}"}\NormalTok{,}
      \StringTok{"Longitude: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(lon, }\DecValTok{3}\NormalTok{), }\StringTok{"\textless{}br/\textgreater{}"}\NormalTok{,}
      \StringTok{"Latitude: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(lat, }\DecValTok{3}\NormalTok{)}
\NormalTok{    )}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{addCircleMarkers}\NormalTok{(}
    \AttributeTok{lng =} \SpecialCharTok{\textasciitilde{}}\NormalTok{lon,}
    \AttributeTok{lat =} \SpecialCharTok{\textasciitilde{}}\NormalTok{lat,}
    \AttributeTok{radius =} \DecValTok{2}\NormalTok{,}
    \AttributeTok{stroke =} \ConstantTok{TRUE}\NormalTok{,}
    \AttributeTok{color =} \StringTok{"\#B0B0B0"}\NormalTok{,}
    \AttributeTok{weight =} \DecValTok{1}\NormalTok{,}
    \AttributeTok{fillColor =} \StringTok{"\#FFF7E6"}\NormalTok{,}
    \AttributeTok{fillOpacity =} \FloatTok{0.5}\NormalTok{,}
    \AttributeTok{popup =} \SpecialCharTok{\textasciitilde{}}\FunctionTok{paste0}\NormalTok{(}
      \StringTok{"\textless{}strong\textgreater{}"}\NormalTok{, name, }\StringTok{" County centroid\textless{}/strong\textgreater{}\textless{}br/\textgreater{}"}\NormalTok{,}
      \StringTok{"Mean T\textless{}sub\textgreater{}max\textless{}/sub\textgreater{}: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(mean\_tmmx\_C, }\DecValTok{1}\NormalTok{), }\StringTok{" °C\textless{}br/\textgreater{}"}\NormalTok{,}
      \StringTok{"Lon: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(lon, }\DecValTok{3}\NormalTok{), }\StringTok{", Lat: "}\NormalTok{, }\FunctionTok{round}\NormalTok{(lat, }\DecValTok{3}\NormalTok{)}
\NormalTok{    )}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  
  \FunctionTok{addLegend}\NormalTok{(}
    \AttributeTok{position =} \StringTok{"bottomright"}\NormalTok{,}
    \AttributeTok{pal      =}\NormalTok{ pal,}
    \AttributeTok{values   =} \SpecialCharTok{\textasciitilde{}}\NormalTok{mean\_tmmx\_C,}
    \AttributeTok{title    =} \StringTok{"Mean T\textless{}sub\textgreater{}max\textless{}/sub\textgreater{} (°C)"}\NormalTok{,}
    \AttributeTok{labFormat =} \FunctionTok{labelFormat}\NormalTok{(}\AttributeTok{digits =} \DecValTok{1}\NormalTok{)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/interactive_temperature_map-1.pdf}}

County polygons are shaded according to the multi‑year mean daily
maximum temperature (°C), with warmer colours indicating higher
long‑term averages, and blue markers denoting county centroids. This
interactive figure allows detailed exploration of the spatial
heterogeneity in temperature across New York State and facilitates
linking local climatic conditions to downstream health or environmental
outcomes.

\subsection{Supplement Materials}\label{supplement-materials}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"If you would like to explore additional variables in our dataset, please click [Data Presentation](https://xucy2347.shinyapps.io/NYmeteor\_dashboard/) to view more details."}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

If you would like to explore additional variables in our dataset, please
click \href{https://xucy2347.shinyapps.io/NYmeteor_dashboard/}{Data
Presentation} to view more details.

\section{\texorpdfstring{\textbf{K-means clustering and
PCA}}{K-means clustering and PCA}}\label{k-means-clustering-and-pca}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\NormalTok{opts\_chunk}\SpecialCharTok{$}\FunctionTok{set}\NormalTok{(}\AttributeTok{message =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{warning =} \ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(lubridate)}
\FunctionTok{library}\NormalTok{(sf)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(factoextra)}
\FunctionTok{library}\NormalTok{(ggplot2)}

\NormalTok{county\_fips\_df }\OtherTok{\textless{}{-}} \FunctionTok{st\_read}\NormalTok{(}\StringTok{"df\_gen/data/NYcounty\_fips"}\NormalTok{, }\AttributeTok{quiet =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{weather }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"df\_gen/data/meteor\_2016to20\_NY.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Methodology}\label{methodology}

\subsubsection{Data Processing and Feature
Construction}\label{data-processing-and-feature-construction}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{weather2 }\OtherTok{\textless{}{-}}\NormalTok{ weather }\SpecialCharTok{|\textgreater{}}
\FunctionTok{mutate}\NormalTok{(}
\AttributeTok{tmmx\_c =}\NormalTok{ tmmx }\SpecialCharTok{{-}} \FloatTok{273.15}\NormalTok{,}
\AttributeTok{tmmn\_c =}\NormalTok{ tmmn }\SpecialCharTok{{-}} \FloatTok{273.15}\NormalTok{,}
\AttributeTok{year   =} \FunctionTok{year}\NormalTok{(date),}
\AttributeTok{month  =} \FunctionTok{month}\NormalTok{(date)}
\NormalTok{)}

\NormalTok{county\_feat }\OtherTok{\textless{}{-}}\NormalTok{ weather2 }\SpecialCharTok{|\textgreater{}}
\FunctionTok{group\_by}\NormalTok{(county) }\SpecialCharTok{|\textgreater{}}
\FunctionTok{summarise}\NormalTok{(}
\AttributeTok{mean\_tmmx\_c =} \FunctionTok{mean}\NormalTok{(tmmx\_c, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{mean\_tmmn\_c =} \FunctionTok{mean}\NormalTok{(tmmn\_c, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{mean\_rmax   =} \FunctionTok{mean}\NormalTok{(rmax,   }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{mean\_vpd    =} \FunctionTok{mean}\NormalTok{(vpd,    }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{mean\_pr     =} \FunctionTok{mean}\NormalTok{(pr,     }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{mean\_srad   =} \FunctionTok{mean}\NormalTok{(srad,   }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{mean\_vs     =} \FunctionTok{mean}\NormalTok{(vs,     }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We summarized daily meteorological records from 2016--2020 into
county-level ``climate profiles.'' For each county, we computed
long-term averages of maximum and minimum temperature, maximum relative
humidity, vapor pressure deficit, precipitation, solar radiation, and
wind speed. This aggregation yields one observation per county
representing its typical climate over the study period.

\subsubsection{Standardization}\label{standardization}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{feat\_mat }\OtherTok{\textless{}{-}}\NormalTok{ county\_feat }\SpecialCharTok{|\textgreater{}}
\FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{county) }\SpecialCharTok{|\textgreater{}}
\FunctionTok{scale}\NormalTok{() }\SpecialCharTok{|\textgreater{}}
\FunctionTok{as.matrix}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

Before clustering, all continuous features were standardized to mean 0
and unit variance so that no single variable dominated the distance
calculations in k-means.

\subsection{Clustering Approach}\label{clustering-approach}

\subsubsection{Choice of the Number of
Clusters}\label{choice-of-the-number-of-clusters}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}

\FunctionTok{fviz\_nbclust}\NormalTok{(feat\_mat, kmeans, }\AttributeTok{method =} \StringTok{"wss"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/unnamed-chunk-10-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_nbclust}\NormalTok{(feat\_mat, kmeans, }\AttributeTok{method =} \StringTok{"silhouette"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/unnamed-chunk-10-2.pdf}}

We chose k=2 based on both the elbow and silhouette criteria. In the WSS
(elbow) plot, the largest drop occurs between k=1 and k=2/3, and the
curve flattens after k=2, indicating limited gain from additional
clusters. The average silhouette width is highest at k=2, suggesting
that two clusters provide the best separation and cohesion.

\subsubsection{K-means Clustering
Results}\label{k-means-clustering-results}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(gt)}

\NormalTok{cluster\_table }\OtherTok{\textless{}{-}}\NormalTok{ cluster\_summary }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{cluster =} \FunctionTok{if\_else}\NormalTok{(cluster }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\StringTok{"Cluster 1"}\NormalTok{, }\StringTok{"Cluster 2"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{gt}\NormalTok{(}\AttributeTok{rowname\_col =} \StringTok{"cluster"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{tab\_header}\NormalTok{(}
    \AttributeTok{title =} \FunctionTok{md}\NormalTok{(}\StringTok{"**Climate characteristics by cluster**"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{cols\_label}\NormalTok{(}
    \AttributeTok{n\_counties  =} \StringTok{"n"}\NormalTok{,}
    \AttributeTok{mean\_tmmx\_c =} \StringTok{"Mean tmmx (°C)"}\NormalTok{,}
    \AttributeTok{mean\_tmmn\_c =} \StringTok{"Mean tmmn (°C)"}\NormalTok{,}
    \AttributeTok{mean\_rmax   =} \StringTok{"Mean rmax (\%)"}\NormalTok{,}
    \AttributeTok{mean\_vpd    =} \StringTok{"Mean VPD (kPa)"}\NormalTok{,}
    \AttributeTok{mean\_pr     =} \StringTok{"Mean precip (mm)"}\NormalTok{,}
    \AttributeTok{mean\_srad   =} \StringTok{"Mean srad (W/m²)"}\NormalTok{,}
    \AttributeTok{mean\_vs     =} \StringTok{"Mean wind (m/s)"}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{fmt\_number}\NormalTok{(}
    \AttributeTok{columns =} \FunctionTok{c}\NormalTok{(mean\_tmmx\_c}\SpecialCharTok{:}\NormalTok{mean\_vs),}
    \AttributeTok{decimals =} \DecValTok{2}
\NormalTok{  ) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{tab\_options}\NormalTok{(}
    \AttributeTok{table.font.size =} \FunctionTok{px}\NormalTok{(}\DecValTok{14}\NormalTok{),}
    \AttributeTok{data\_row.padding =} \FunctionTok{px}\NormalTok{(}\DecValTok{4}\NormalTok{)}
\NormalTok{  )}

\NormalTok{cluster\_table}
\end{Highlighting}
\end{Shaded}

\begin{table}[t]
\caption*{
{\fontsize{20}{25}\selectfont  \textbf{Climate characteristics by cluster}\fontsize{10}{13}\selectfont }
} 
\fontsize{10.0pt}{13.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}l|rrrrrrrr}
\toprule
 & n & Mean tmmx (\textdegreeC) & Mean tmmn (\textdegreeC) & Mean rmax (\%) & Mean VPD (kPa) & Mean precip (mm) & Mean srad (W/m\texttwosuperior) & Mean wind (m/s) \\ 
\midrule\addlinespace[2.5pt]
Cluster 1 & 9 & 17.02 & 8.37 & 81.06 & 0.65 & 3.49 & 187.13 & 4.88 \\ 
Cluster 2 & 53 & 13.77 & 3.00 & 89.54 & 0.48 & 3.14 & 168.02 & 4.49 \\ 
\bottomrule
\end{tabular*}
\end{table}

We identified two clusters of New York counties based on their
2016--2020 average meteorological profiles.

Cluster 1 (n = 9) exhibits warmer and sunnier conditions, with higher
mean daily maximum and minimum temperature (approximately 17.0°C and
8.4°C) compared with Cluster 2 (13.8°C and 3.0°C).

Cluster 1 also has lower maximum relative humidity and higher vapor
pressure deficit, indicating relatively drier air, alongside slightly
higher precipitation, stronger solar radiation, and higher wind speed.

Cluster 2 (n = 53), which contains most counties, is characterized by
cooler temperatures, higher humidity, lower solar radiation, and
slightly weaker winds.

Thus, Cluster 1 can be interpreted as a ``warmer, sunnier, relatively
drier'' climate type, whereas Cluster 2 represents a ``cooler, more
humid'' climate type.

\subsubsection{Principal Component
Analysis}\label{principal-component-analysis}

From the perspective of these data, PCA is useful because there are many
correlated climate features at the county level.

Considering all seven variables separately makes it difficult to see the
overall structure of the data or to understand how the k-means clusters
differ in the multivariate space.

PCA provides a set of uncorrelated components that summarize the main
gradients of climate variation, allowing us to visualize the data in
only two dimensions.

We focus on PC1 and PC2 because they explain the largest share of total
variance and therefore capture the most important patterns in the
climate features.

PC1 (horizontal axis) represents the primary gradient of climate
variation. Counties in Cluster 1 and Cluster 2 fall on opposite sides,
so PC1 separates warmer, sunnier, relatively drier counties from cooler,
more humid counties.

PC2 (vertical axis) captures additional variation not explained by PC1,
such as smaller differences in humidity, precipitation, radiation, and
wind speed, and helps show within-cluster heterogeneity.

\subsubsection{Visualization of Climate-Based
Clusters}\label{visualization-of-climate-based-clusters}

After choosing k=2, we used three complementary plots to evaluate
whether the clusters are meaningful and how they differ:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  How do the original climate variables differ by cluster?
\item
  Do the clusters separate well in the multivariate feature space?
\item
  How are the clusters distributed geographically across New York State?
\end{enumerate}

\paragraph{Figure 1: Distribution of Climate Features by
Cluster}\label{figure-1-distribution-of-climate-features-by-cluster}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot\_data }\OtherTok{\textless{}{-}}\NormalTok{ county\_cluster }\SpecialCharTok{|\textgreater{}}
\FunctionTok{select}\NormalTok{(county, cluster, mean\_tmmx\_c}\SpecialCharTok{:}\NormalTok{mean\_vs) }\SpecialCharTok{|\textgreater{}}
\FunctionTok{pivot\_longer}\NormalTok{(}
\AttributeTok{cols =} \SpecialCharTok{{-}}\FunctionTok{c}\NormalTok{(county, cluster),}
\AttributeTok{names\_to =} \StringTok{"variable"}\NormalTok{,}
\AttributeTok{values\_to =} \StringTok{"value"}
\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(plot\_data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ cluster, }\AttributeTok{y =}\NormalTok{ value, }\AttributeTok{fill =}\NormalTok{ cluster)) }\SpecialCharTok{+}
\FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ variable, }\AttributeTok{scales =} \StringTok{"free\_y"}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{theme\_bw}\NormalTok{() }\SpecialCharTok{+}
\FunctionTok{labs}\NormalTok{(}
\AttributeTok{x =} \StringTok{"Cluster"}\NormalTok{,}
\AttributeTok{y =} \StringTok{"Value"}\NormalTok{,}
\AttributeTok{title =} \StringTok{"Distribution of climate features by cluster"}
\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/unnamed-chunk-13-1.pdf}}

The faceted boxplots show the distribution of each county-level climate
feature by cluster.

They highlight that Cluster 1 counties tend to have higher mean maximum
and minimum temperatures, higher solar radiation and wind speed,
slightly higher precipitation, lower maximum relative humidity, and
higher vapor pressure deficit than Cluster 2, making the ``warm, sunny,
relatively dry'' vs ``cooler, more humid'' contrast clear on the
original scale of the variables.

\paragraph{Figure 2: PCA of County-Level Climate
Features}\label{figure-2-pca-of-county-level-climate-features}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pca\_fit }\OtherTok{\textless{}{-}} \FunctionTok{prcomp}\NormalTok{(feat\_mat, }\AttributeTok{center =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{scale. =} \ConstantTok{FALSE}\NormalTok{)}

\NormalTok{pca\_df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(pca\_fit}\SpecialCharTok{$}\NormalTok{x[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{]) }\SpecialCharTok{|\textgreater{}}
\FunctionTok{mutate}\NormalTok{(}
\AttributeTok{county  =}\NormalTok{ county\_feat}\SpecialCharTok{$}\NormalTok{county,}
\AttributeTok{cluster =}\NormalTok{ county\_cluster}\SpecialCharTok{$}\NormalTok{cluster}
\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(pca\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ PC1, }\AttributeTok{y =}\NormalTok{ PC2, }\AttributeTok{color =}\NormalTok{ cluster)) }\SpecialCharTok{+}
\FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
\FunctionTok{labs}\NormalTok{(}
\AttributeTok{title =} \StringTok{"PCA of county{-}level climate features"}\NormalTok{,}
\AttributeTok{x =} \StringTok{"PC1"}\NormalTok{,}
\AttributeTok{y =} \StringTok{"PC2"}\NormalTok{,}
\AttributeTok{color =} \StringTok{"Cluster"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/unnamed-chunk-14-1.pdf}}

The PCA plot projects all standardized features onto the first two
principal components and colors points by cluster.

Cluster 1 counties cluster together on one side of the PC1 axis, while
Cluster 2 counties occupy a separate region, indicating that the two
clusters are well separated in the reduced multivariate climate space.

\paragraph{Figure 3: Spatial Distribution of Climate
Clusters}\label{figure-3-spatial-distribution-of-climate-clusters}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{county\_cluster2 }\OtherTok{\textless{}{-}}\NormalTok{ county\_cluster }\SpecialCharTok{|\textgreater{}}
\FunctionTok{mutate}\NormalTok{(}\AttributeTok{fips =} \FunctionTok{as.character}\NormalTok{(county))}

\NormalTok{ny\_sf2 }\OtherTok{\textless{}{-}}\NormalTok{ county\_fips\_df }\SpecialCharTok{|\textgreater{}}
\FunctionTok{mutate}\NormalTok{(}\AttributeTok{fips =} \FunctionTok{as.character}\NormalTok{(fips))}

\NormalTok{ny\_map }\OtherTok{\textless{}{-}}\NormalTok{ ny\_sf2 }\SpecialCharTok{|\textgreater{}}
\FunctionTok{left\_join}\NormalTok{(county\_cluster2, }\AttributeTok{by =} \StringTok{"fips"}\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(ny\_map) }\SpecialCharTok{+}
\FunctionTok{geom\_sf}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ cluster), }\AttributeTok{color =} \StringTok{"white"}\NormalTok{, }\AttributeTok{size =} \FloatTok{0.2}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{scale\_fill\_brewer}\NormalTok{(}\AttributeTok{palette =} \StringTok{"Set2"}\NormalTok{, }\AttributeTok{name =} \StringTok{"Cluster"}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
\FunctionTok{labs}\NormalTok{(}
\AttributeTok{title =} \StringTok{"Climate{-}based clusters of New York counties (k = 2)"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/unnamed-chunk-15-1.pdf}}

The choropleth map joins cluster labels to the county shapefile and
shows that Cluster 1 counties are concentrated in the downstate/NYC and
Long Island region, whereas most upstate and interior counties belong to
Cluster 2.

This confirms that the climate-based clusters also align with intuitive
coastal vs inland geographic patterns.

\subsection{Summary}\label{summary}

Combining k-means clustering with PCA and spatial visualization
demonstrates that New York counties can be grouped into two distinct
climate types.

The first cluster represents warmer, sunnier, relatively drier coastal
counties, while the second cluster captures cooler, more humid interior
counties.

These patterns are consistent across the original climate features, the
low-dimensional PCA representation, and the geographic distribution.

\section{\texorpdfstring{\textbf{Prediction
Models}}{Prediction Models}}\label{prediction-models}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readr)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(lubridate)}
\FunctionTok{library}\NormalTok{(forecast)}
\FunctionTok{library}\NormalTok{(tidyr)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(tibble)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(forecast)}
\FunctionTok{library}\NormalTok{(lubridate)}
\FunctionTok{library}\NormalTok{(xgboost)}
\FunctionTok{library}\NormalTok{(stats)}
\FunctionTok{library}\NormalTok{(grid) }
\end{Highlighting}
\end{Shaded}

\subsection{Model 1}\label{model-1}

\subsubsection{Data preparation}\label{data-preparation}

In this section we aggregate station‐level meteorological data to the
New York State level and create lagged covariates that will be used as
external regressors in the ARIMAX model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_raw }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"df\_gen/data/meteor\_2016to20\_NY.csv"}\NormalTok{)}
\NormalTok{dat }\OtherTok{\textless{}{-}}\NormalTok{ data\_raw }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{tmmx =}\NormalTok{ tmmx }\SpecialCharTok{{-}} \FloatTok{273.15}\NormalTok{,}
    \AttributeTok{tmmn =}\NormalTok{ tmmn }\SpecialCharTok{{-}} \FloatTok{273.15}\NormalTok{,}
    \AttributeTok{year   =} \FunctionTok{year}\NormalTok{(date),}
    \AttributeTok{month  =} \FunctionTok{month}\NormalTok{(date)}
\NormalTok{  )}
\NormalTok{dat\_state }\OtherTok{\textless{}{-}}\NormalTok{ dat }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{group\_by}\NormalTok{(date) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{summarise}\NormalTok{(}
\AttributeTok{tmmx =} \FunctionTok{mean}\NormalTok{(tmmx, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{sph  =} \FunctionTok{mean}\NormalTok{(sph,  }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{vpd  =} \FunctionTok{mean}\NormalTok{(vpd,  }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{srad =} \FunctionTok{mean}\NormalTok{(srad, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{vs   =} \FunctionTok{mean}\NormalTok{(vs,   }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{arrange}\NormalTok{(date)}

\NormalTok{dat\_state\_lag }\OtherTok{\textless{}{-}}\NormalTok{ dat\_state }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{mutate}\NormalTok{(}
\AttributeTok{sph\_lag1  =}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{lag}\NormalTok{(sph,  }\DecValTok{1}\NormalTok{),}
\AttributeTok{vpd\_lag1  =}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{lag}\NormalTok{(vpd,  }\DecValTok{1}\NormalTok{),}
\AttributeTok{srad\_lag1 =}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{lag}\NormalTok{(srad, }\DecValTok{1}\NormalTok{),}
\AttributeTok{vs\_lag1   =}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{lag}\NormalTok{(vs,   }\DecValTok{1}\NormalTok{)}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{tidyr}\SpecialCharTok{::}\FunctionTok{drop\_na}\NormalTok{()}

\NormalTok{start\_year }\OtherTok{\textless{}{-}} \FunctionTok{year}\NormalTok{(}\FunctionTok{min}\NormalTok{(dat\_state\_lag}\SpecialCharTok{$}\NormalTok{date))}
\NormalTok{start\_doy  }\OtherTok{\textless{}{-}} \FunctionTok{yday}\NormalTok{(}\FunctionTok{min}\NormalTok{(dat\_state\_lag}\SpecialCharTok{$}\NormalTok{date))}

\NormalTok{tmmx\_ts }\OtherTok{\textless{}{-}} \FunctionTok{ts}\NormalTok{(}
\NormalTok{dat\_state\_lag}\SpecialCharTok{$}\NormalTok{tmmx,}
\AttributeTok{start     =} \FunctionTok{c}\NormalTok{(start\_year, start\_doy),}
\AttributeTok{frequency =} \DecValTok{365}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{ARIMAX + Fourier model}\label{arimax-fourier-model}

To represent strong annual seasonality, we use Fourier terms instead of
a seasonal ARIMA structure. These Fourier harmonics, together with
lagged meteorological covariates, enter the model as external
regressors, while the error term follows a non-seasonal ARIMA process
selected by auto.arima().

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{K }\OtherTok{\textless{}{-}} \DecValTok{3}
\NormalTok{fourier\_terms }\OtherTok{\textless{}{-}} \FunctionTok{fourier}\NormalTok{(tmmx\_ts, }\AttributeTok{K =}\NormalTok{ K)}
\NormalTok{xreg }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}
\NormalTok{fourier\_terms,}
\AttributeTok{sph\_lag1  =}\NormalTok{ dat\_state\_lag}\SpecialCharTok{$}\NormalTok{sph\_lag1,}
\AttributeTok{vpd\_lag1  =}\NormalTok{ dat\_state\_lag}\SpecialCharTok{$}\NormalTok{vpd\_lag1,}
\AttributeTok{srad\_lag1 =}\NormalTok{ dat\_state\_lag}\SpecialCharTok{$}\NormalTok{srad\_lag1,}
\AttributeTok{vs\_lag1   =}\NormalTok{ dat\_state\_lag}\SpecialCharTok{$}\NormalTok{vs\_lag1}
\NormalTok{)}

\NormalTok{fit\_arimax\_fourier }\OtherTok{\textless{}{-}} \FunctionTok{auto.arima}\NormalTok{(}
\NormalTok{tmmx\_ts,}
\AttributeTok{xreg     =}\NormalTok{ xreg,}
\AttributeTok{seasonal =} \ConstantTok{FALSE}
\NormalTok{)}
\NormalTok{model\_info }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{Metric =} \FunctionTok{c}\NormalTok{(}\StringTok{"Log{-}Likelihood"}\NormalTok{, }\StringTok{"Sigma\^{}2"}\NormalTok{, }\StringTok{"AIC"}\NormalTok{, }\StringTok{"AICc"}\NormalTok{, }\StringTok{"BIC"}\NormalTok{),}
  \AttributeTok{Value =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{logLik}\NormalTok{(fit\_arimax\_fourier)),}
\NormalTok{    fit\_arimax\_fourier}\SpecialCharTok{$}\NormalTok{sigma2,}
\NormalTok{    fit\_arimax\_fourier}\SpecialCharTok{$}\NormalTok{aic,}
\NormalTok{    fit\_arimax\_fourier}\SpecialCharTok{$}\NormalTok{aicc,}
\NormalTok{    fit\_arimax\_fourier}\SpecialCharTok{$}\NormalTok{bic}
\NormalTok{  )}
\NormalTok{)}

\FunctionTok{kable}\NormalTok{(}
\NormalTok{model\_info,}
\AttributeTok{digits =} \DecValTok{4}\NormalTok{,}
\AttributeTok{caption =} \StringTok{"Overall fit statistics for the ARIMAX + Fourier model"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lr@{}}
\caption{Overall fit statistics for the ARIMAX + Fourier
model}\tabularnewline
\toprule\noalign{}
Metric & Value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Metric & Value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Log-Likelihood & -4819.6440 \\
Sigma\^{}2 & 11.5696 \\
AIC & 9669.2880 \\
AICc & 9669.5532 \\
BIC & 9751.9363 \\
\end{longtable}

In this specification, the ARIMA component captures short-term temporal
dependence, while Fourier terms describe the smooth annual cycle. Lagged
humidity, vapor-pressure deficit, solar radiation, and wind speed
account for additional meteorological drivers of temperature.

\subsubsection{Coefficient summary}\label{coefficient-summary}

We present the estimated coefficients and standard errors for the AR
terms, meteorological covariates, and Fourier harmonics.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{coef\_est }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(fit\_arimax\_fourier)}
\NormalTok{se\_est   }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{diag}\NormalTok{(}\FunctionTok{vcov}\NormalTok{(fit\_arimax\_fourier)))}

\NormalTok{coef\_tbl }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
\AttributeTok{Term     =} \FunctionTok{names}\NormalTok{(coef\_est),}
\AttributeTok{Estimate =} \FunctionTok{as.numeric}\NormalTok{(coef\_est),}
\AttributeTok{SE       =} \FunctionTok{as.numeric}\NormalTok{(se\_est)}
\NormalTok{)}

\FunctionTok{kable}\NormalTok{(}
\NormalTok{coef\_tbl,}
\AttributeTok{digits =} \DecValTok{4}\NormalTok{,}
\AttributeTok{caption =} \StringTok{"Coefficient estimates for ARIMAX + Fourier model"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrr@{}}
\caption{Coefficient estimates for ARIMAX + Fourier
model}\tabularnewline
\toprule\noalign{}
Term & Estimate & SE \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Term & Estimate & SE \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
ar1 & 0.7726 & 0.0410 \\
ar2 & -0.2497 & 0.0375 \\
ar3 & 0.1078 & 0.0241 \\
intercept & 16.4607 & 0.9516 \\
S1-365 & -4.5286 & 0.3896 \\
C1-365 & -12.3698 & 0.7226 \\
S2-365 & 0.5384 & 0.3231 \\
C2-365 & -0.4380 & 0.3095 \\
S3-365 & 0.5627 & 0.3020 \\
C3-365 & -0.3102 & 0.3016 \\
sph\_lag1 & -47.3621 & 101.2496 \\
vpd\_lag1 & 0.1925 & 0.5844 \\
srad\_lag1 & 0.0015 & 0.0023 \\
vs\_lag1 & -0.4976 & 0.0547 \\
\end{longtable}

\subsubsection{Model Diagnostics}\label{model-diagnostics}

We assess model adequacy by examining residuals. Ideally, residuals
should behave like uncorrelated noise with no systematic temporal
pattern.

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/ljung-table-1.pdf}}

\begin{longtable}[]{@{}rrrrr@{}}
\caption{Ljung--Box Test for ARIMAX + Fourier Residuals}\tabularnewline
\toprule\noalign{}
Statistic & Degrees.of.freedom & P.value & Model.df & Total.lags.used \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Statistic & Degrees.of.freedom & P.value & Model.df & Total.lags.used \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
330.1 & 362 & 0.8844 & 3 & 365 \\
\end{longtable}

The residual time series shows no obvious structure, the autocorrelation
function remains within the 95\% bounds at most lags, and the Ljung--Box
test is non-significant. Together, these diagnostics suggest that the
ARIMAX + Fourier model has captured most of the temporal dependence and
seasonal pattern in the data, and the remaining residuals are
approximately white noise.

\subsubsection{Forecasting and
Interpretation}\label{forecasting-and-interpretation}

We generate multi-step-ahead forecasts using the fitted ARIMAX + Fourier
model. Future Fourier terms are constructed analytically, and recent
lagged covariates are used to build the regressor matrix for the
forecast horizon.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{h }\OtherTok{\textless{}{-}} \DecValTok{730}
\NormalTok{fourier\_future }\OtherTok{\textless{}{-}} \FunctionTok{fourier}\NormalTok{(tmmx\_ts, }\AttributeTok{K =}\NormalTok{ K, }\AttributeTok{h =}\NormalTok{ h)}

\NormalTok{recent\_block }\OtherTok{\textless{}{-}}\NormalTok{ dat\_state\_lag }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{slice\_tail}\NormalTok{(}\AttributeTok{n =} \DecValTok{365}\NormalTok{)}

\NormalTok{xreg\_future }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}
\NormalTok{fourier\_future,}
\AttributeTok{sph\_lag1  =}\NormalTok{ recent\_block}\SpecialCharTok{$}\NormalTok{sph\_lag1,}
\AttributeTok{vpd\_lag1  =}\NormalTok{ recent\_block}\SpecialCharTok{$}\NormalTok{vpd\_lag1,}
\AttributeTok{srad\_lag1 =}\NormalTok{ recent\_block}\SpecialCharTok{$}\NormalTok{srad\_lag1,}
\AttributeTok{vs\_lag1   =}\NormalTok{ recent\_block}\SpecialCharTok{$}\NormalTok{vs\_lag1}
\NormalTok{)}

\NormalTok{fc }\OtherTok{\textless{}{-}} \FunctionTok{forecast}\NormalTok{(fit\_arimax\_fourier, }\AttributeTok{xreg =}\NormalTok{ xreg\_future, }\AttributeTok{h =}\NormalTok{ h)}

\FunctionTok{autoplot}\NormalTok{(fc) }\SpecialCharTok{+}
\FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Two{-}Year ARIMAX + Fourier Forecast for Daily Maximum Temperature"}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{xlab}\NormalTok{(}\StringTok{"Time"}\NormalTok{) }\SpecialCharTok{+}
\FunctionTok{ylab}\NormalTok{(}\StringTok{"tmmx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/unnamed-chunk-20-1.pdf}}

The figure presents a two-year forecast of daily maximum temperature
derived from an ARIMAX model augmented with Fourier seasonal terms. The
historical portion of the time series (black) exhibits strong annual
cycles and substantial short-term variability, both of which are
captured by the model. The forecasted values (blue) follow a smooth,
periodic pattern consistent with the dominant seasonal structure. The
incorporation of Fourier harmonics allows the model to represent complex
seasonal behavior more flexibly than classical seasonal ARIMA, resulting
in coherent long-range forecasts that align with the historical
climatological patterns.

\subsection{Model 2}\label{model-2}

\subsubsection{Data Preparation}\label{data-preparation-1}

Daily statewide averages for all available meteorological variables were
computed. Feature engineering included lag terms, rolling means, and
time-based indicators (day of year, weekday, year), which help XGBoost
capture temporal dependencies and short-term memory effects.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat }\OtherTok{\textless{}{-}}\NormalTok{ dat }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{mutate}\NormalTok{(}\AttributeTok{date =} \FunctionTok{as.Date}\NormalTok{(date))}

\NormalTok{dat\_state }\OtherTok{\textless{}{-}}\NormalTok{ dat }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{group\_by}\NormalTok{(date) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{summarise}\NormalTok{(}
\AttributeTok{tmmx =} \FunctionTok{mean}\NormalTok{(tmmx, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{tmmn =} \FunctionTok{mean}\NormalTok{(tmmn, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{sph  =} \FunctionTok{mean}\NormalTok{(sph,  }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{vpd  =} \FunctionTok{mean}\NormalTok{(vpd,  }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{pr   =} \FunctionTok{mean}\NormalTok{(pr,   }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{rmin =} \FunctionTok{mean}\NormalTok{(rmin, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{rmax =} \FunctionTok{mean}\NormalTok{(rmax, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{srad =} \FunctionTok{mean}\NormalTok{(srad, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{vs   =} \FunctionTok{mean}\NormalTok{(vs,   }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
\AttributeTok{th   =} \FunctionTok{mean}\NormalTok{(th,   }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{ungroup}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{arrange}\NormalTok{(date)}


\NormalTok{dat\_ml }\OtherTok{\textless{}{-}}\NormalTok{ dat\_state }\SpecialCharTok{\%\textgreater{}\%}
\FunctionTok{mutate}\NormalTok{(}
\AttributeTok{doy =} \FunctionTok{yday}\NormalTok{(date),}
\AttributeTok{dow =} \FunctionTok{wday}\NormalTok{(date, }\AttributeTok{week\_start =} \DecValTok{1}\NormalTok{),}
\AttributeTok{year =} \FunctionTok{year}\NormalTok{(date),}
\AttributeTok{tmmx\_lag1 =} \FunctionTok{lag}\NormalTok{(tmmx, }\DecValTok{1}\NormalTok{),}
\AttributeTok{tmmx\_lag2 =} \FunctionTok{lag}\NormalTok{(tmmx, }\DecValTok{2}\NormalTok{),}
\AttributeTok{tmmx\_lag7 =} \FunctionTok{lag}\NormalTok{(tmmx, }\DecValTok{7}\NormalTok{),}
\AttributeTok{tmmn\_lag1 =} \FunctionTok{lag}\NormalTok{(tmmn, }\DecValTok{1}\NormalTok{),}
\AttributeTok{sph\_lag1  =} \FunctionTok{lag}\NormalTok{(sph, }\DecValTok{1}\NormalTok{),}
\AttributeTok{vpd\_lag1  =} \FunctionTok{lag}\NormalTok{(vpd, }\DecValTok{1}\NormalTok{),}
\AttributeTok{pr\_lag1   =} \FunctionTok{lag}\NormalTok{(pr, }\DecValTok{1}\NormalTok{),}
\AttributeTok{rmin\_lag1 =} \FunctionTok{lag}\NormalTok{(rmin, }\DecValTok{1}\NormalTok{),}
\AttributeTok{rmax\_lag1 =} \FunctionTok{lag}\NormalTok{(rmax, }\DecValTok{1}\NormalTok{),}
\AttributeTok{srad\_lag1 =} \FunctionTok{lag}\NormalTok{(srad, }\DecValTok{1}\NormalTok{),}
\AttributeTok{vs\_lag1   =} \FunctionTok{lag}\NormalTok{(vs, }\DecValTok{1}\NormalTok{)}
\NormalTok{)}

\NormalTok{dat\_ml}\SpecialCharTok{$}\NormalTok{tmmx\_roll7 }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(stats}\SpecialCharTok{::}\FunctionTok{filter}\NormalTok{(dat\_ml}\SpecialCharTok{$}\NormalTok{tmmx, }\FunctionTok{rep}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\DecValTok{7}\NormalTok{, }\DecValTok{7}\NormalTok{), }\AttributeTok{sides =} \DecValTok{1}\NormalTok{))}

\NormalTok{dat\_ml }\OtherTok{\textless{}{-}}\NormalTok{ dat\_ml }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{drop\_na}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\subsubsection{XGBoost Model}\label{xgboost-model}

The dataset was split chronologically (80\% training, 20\% testing). An
XGBoost regression model was trained using RMSE as the optimization
metric and early stopping to prevent overfitting.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{split\_date }\OtherTok{\textless{}{-}}\NormalTok{ dat\_ml}\SpecialCharTok{$}\NormalTok{date[}\FunctionTok{floor}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(dat\_ml) }\SpecialCharTok{*} \FloatTok{0.8}\NormalTok{)]}
\NormalTok{train\_df   }\OtherTok{\textless{}{-}}\NormalTok{ dat\_ml }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(date }\SpecialCharTok{\textless{}=}\NormalTok{ split\_date)}
\NormalTok{test\_df    }\OtherTok{\textless{}{-}}\NormalTok{ dat\_ml }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(date }\SpecialCharTok{\textgreater{}}\NormalTok{  split\_date)}

\NormalTok{feature\_cols }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"tmmn"}\NormalTok{,}\StringTok{"sph"}\NormalTok{,}\StringTok{"vpd"}\NormalTok{,}\StringTok{"pr"}\NormalTok{,}\StringTok{"rmin"}\NormalTok{,}\StringTok{"rmax"}\NormalTok{,}\StringTok{"srad"}\NormalTok{,}\StringTok{"vs"}\NormalTok{,}\StringTok{"th"}\NormalTok{,}
  \StringTok{"tmmx\_lag1"}\NormalTok{,}\StringTok{"tmmx\_lag2"}\NormalTok{,}\StringTok{"tmmx\_lag7"}\NormalTok{,}
  \StringTok{"tmmn\_lag1"}\NormalTok{,}\StringTok{"sph\_lag1"}\NormalTok{,}\StringTok{"vpd\_lag1"}\NormalTok{,}\StringTok{"pr\_lag1"}\NormalTok{,}
  \StringTok{"rmin\_lag1"}\NormalTok{,}\StringTok{"rmax\_lag1"}\NormalTok{,}\StringTok{"srad\_lag1"}\NormalTok{,}\StringTok{"vs\_lag1"}\NormalTok{,}
  \StringTok{"tmmx\_roll7"}\NormalTok{,}\StringTok{"doy"}\NormalTok{,}\StringTok{"dow"}\NormalTok{,}\StringTok{"year"}
\NormalTok{)}

\NormalTok{train\_x }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(train\_df[, feature\_cols])}
\NormalTok{train\_y }\OtherTok{\textless{}{-}}\NormalTok{ train\_df}\SpecialCharTok{$}\NormalTok{tmmx}

\NormalTok{test\_x  }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(test\_df[, feature\_cols])}
\NormalTok{test\_y  }\OtherTok{\textless{}{-}}\NormalTok{ test\_df}\SpecialCharTok{$}\NormalTok{tmmx}

\NormalTok{dtrain }\OtherTok{\textless{}{-}} \FunctionTok{xgb.DMatrix}\NormalTok{(train\_x, }\AttributeTok{label =}\NormalTok{ train\_y)}
\NormalTok{dtest  }\OtherTok{\textless{}{-}} \FunctionTok{xgb.DMatrix}\NormalTok{(test\_x,  }\AttributeTok{label =}\NormalTok{ test\_y)}

\NormalTok{params }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}
  \AttributeTok{objective        =} \StringTok{"reg:squarederror"}\NormalTok{,}
  \AttributeTok{eval\_metric      =} \StringTok{"rmse"}\NormalTok{,}
  \AttributeTok{max\_depth        =} \DecValTok{5}\NormalTok{,}
  \AttributeTok{eta              =} \FloatTok{0.05}\NormalTok{,}
  \AttributeTok{subsample        =} \FloatTok{0.8}\NormalTok{,}
  \AttributeTok{colsample\_bytree =} \FloatTok{0.8}
\NormalTok{)}

\FunctionTok{set.seed}\NormalTok{(}\DecValTok{2025}\NormalTok{)}
\NormalTok{xgb\_model }\OtherTok{\textless{}{-}} \FunctionTok{xgb.train}\NormalTok{(}
  \AttributeTok{params                =}\NormalTok{ params,}
  \AttributeTok{data                  =}\NormalTok{ dtrain,}
  \AttributeTok{nrounds               =} \DecValTok{1500}\NormalTok{,}
  \AttributeTok{evals                 =} \FunctionTok{list}\NormalTok{(}\AttributeTok{train =}\NormalTok{ dtrain, }\AttributeTok{eval =}\NormalTok{ dtest),}
  \AttributeTok{early\_stopping\_rounds =} \DecValTok{50}\NormalTok{,}
  \AttributeTok{verbose               =} \DecValTok{0}   
\NormalTok{)}

\NormalTok{test\_pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(xgb\_model, dtest)}

\NormalTok{test\_df }\OtherTok{\textless{}{-}}\NormalTok{ test\_df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{pred  =}\NormalTok{ test\_pred,}
    \AttributeTok{resid =}\NormalTok{ tmmx }\SpecialCharTok{{-}}\NormalTok{ pred}
\NormalTok{  )}

\NormalTok{rmse }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{((test\_df}\SpecialCharTok{$}\NormalTok{pred }\SpecialCharTok{{-}}\NormalTok{ test\_df}\SpecialCharTok{$}\NormalTok{tmmx)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\NormalTok{mae  }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}\FunctionTok{abs}\NormalTok{(test\_df}\SpecialCharTok{$}\NormalTok{pred }\SpecialCharTok{{-}}\NormalTok{ test\_df}\SpecialCharTok{$}\NormalTok{tmmx))}
\NormalTok{mape }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}\FunctionTok{abs}\NormalTok{((test\_df}\SpecialCharTok{$}\NormalTok{pred }\SpecialCharTok{{-}}\NormalTok{ test\_df}\SpecialCharTok{$}\NormalTok{tmmx) }\SpecialCharTok{/}\NormalTok{ test\_df}\SpecialCharTok{$}\NormalTok{tmmx)) }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{ss\_res }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{((test\_df}\SpecialCharTok{$}\NormalTok{tmmx }\SpecialCharTok{{-}}\NormalTok{ test\_df}\SpecialCharTok{$}\NormalTok{pred)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{ss\_tot }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{((test\_df}\SpecialCharTok{$}\NormalTok{tmmx }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(test\_df}\SpecialCharTok{$}\NormalTok{tmmx))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{r2   }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ ss\_res }\SpecialCharTok{/}\NormalTok{ ss\_tot}

\NormalTok{perf\_xgb }\OtherTok{\textless{}{-}}\NormalTok{ tibble}\SpecialCharTok{::}\FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{Metric =} \FunctionTok{c}\NormalTok{(}\StringTok{"RMSE"}\NormalTok{, }\StringTok{"MAE"}\NormalTok{, }\StringTok{"MAPE (\%)"}\NormalTok{, }\StringTok{"R²"}\NormalTok{),}
  \AttributeTok{Value  =} \FunctionTok{c}\NormalTok{(rmse, mae, mape, r2)}
\NormalTok{)}

\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(perf\_xgb, }\AttributeTok{digits=}\DecValTok{3}\NormalTok{, }\AttributeTok{caption=}\StringTok{"XGBoost Model Performance (Test Set)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lr@{}}
\caption{XGBoost Model Performance (Test Set)}\tabularnewline
\toprule\noalign{}
Metric & Value \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Metric & Value \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
RMSE & 0.574 \\
MAE & 0.435 \\
MAPE (\%) & 112.168 \\
R² & 0.997 \\
\end{longtable}

\subsubsection{Model Diagnostics}\label{model-diagnostics-1}

Residual analysis evaluates whether the model captures structure
adequately and whether remaining errors behave randomly.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p2 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(test\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ tmmx,  }\AttributeTok{color =} \StringTok{"Observed"}\NormalTok{), }\AttributeTok{linewidth =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ pred,  }\AttributeTok{color =} \StringTok{"Predicted"}\NormalTok{), }\AttributeTok{linewidth =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Observed"} \OtherTok{=} \StringTok{"black"}\NormalTok{, }\StringTok{"Predicted"} \OtherTok{=} \StringTok{"blue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Observed vs Predicted (Test Set)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Date"}\NormalTok{, }\AttributeTok{y =} \StringTok{"tmmx"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.title =} \FunctionTok{element\_blank}\NormalTok{(),}
        \AttributeTok{legend.position =} \StringTok{"bottom"}\NormalTok{)}

\NormalTok{p3 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(test\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date, }\AttributeTok{y =}\NormalTok{ resid)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Residuals Over Time"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Date"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Residual"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\NormalTok{acf\_obj }\OtherTok{\textless{}{-}} \FunctionTok{acf}\NormalTok{(test\_df}\SpecialCharTok{$}\NormalTok{resid, }\AttributeTok{plot =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{acf\_df  }\OtherTok{\textless{}{-}} \FunctionTok{with}\NormalTok{(acf\_obj, }\FunctionTok{data.frame}\NormalTok{(}\AttributeTok{lag =}\NormalTok{ lag, }\AttributeTok{acf =}\NormalTok{ acf))}
\NormalTok{n       }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(test\_df}\SpecialCharTok{$}\NormalTok{resid)}
\NormalTok{ci      }\OtherTok{\textless{}{-}} \FloatTok{1.96} \SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n)}

\NormalTok{p5 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(acf\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ lag, }\AttributeTok{y =}\NormalTok{ acf)) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_segment}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xend =}\NormalTok{ lag, }\AttributeTok{yend =} \DecValTok{0}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{ci, ci),}
             \AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{colour =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Residual ACF"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Lag"}\NormalTok{, }\AttributeTok{y =} \StringTok{"ACF"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}

\NormalTok{p4 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(test\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ tmmx, }\AttributeTok{y =}\NormalTok{ pred)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.4}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{intercept =} \DecValTok{0}\NormalTok{,}
              \AttributeTok{colour =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Predicted vs Observed (Test Set)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Observed tmmx"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Predicted tmmx"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\NormalTok{p1 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(test\_df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ resid)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =} \DecValTok{30}\NormalTok{, }\AttributeTok{colour =} \StringTok{"white"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"steelblue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Residual Distribution (Test Set)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Residual"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Count"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}

\NormalTok{multiplot }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(..., }\AttributeTok{plotlist=}\ConstantTok{NULL}\NormalTok{, }\AttributeTok{cols=}\DecValTok{1}\NormalTok{) \{}
  \FunctionTok{library}\NormalTok{(grid)}

\NormalTok{  plots }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{list}\NormalTok{(...), plotlist)}
\NormalTok{  numPlots }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(plots)}

\NormalTok{  layout }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\FunctionTok{seq}\NormalTok{(}\DecValTok{1}\NormalTok{, cols }\SpecialCharTok{*} \FunctionTok{ceiling}\NormalTok{(numPlots }\SpecialCharTok{/}\NormalTok{ cols)),}
                   \AttributeTok{ncol =}\NormalTok{ cols, }\AttributeTok{nrow =} \FunctionTok{ceiling}\NormalTok{(numPlots }\SpecialCharTok{/}\NormalTok{ cols))}

  \FunctionTok{grid.newpage}\NormalTok{()}
  \FunctionTok{pushViewport}\NormalTok{(}\FunctionTok{viewport}\NormalTok{(}\AttributeTok{layout =} \FunctionTok{grid.layout}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(layout), }\FunctionTok{ncol}\NormalTok{(layout))))}
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{numPlots) \{}
\NormalTok{    matchidx }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{which}\NormalTok{(layout }\SpecialCharTok{==}\NormalTok{ i, }\AttributeTok{arr.ind =} \ConstantTok{TRUE}\NormalTok{))}
    \FunctionTok{print}\NormalTok{(plots[[i]], }\AttributeTok{vp =} \FunctionTok{viewport}\NormalTok{(}
      \AttributeTok{layout.pos.row =}\NormalTok{ matchidx}\SpecialCharTok{$}\NormalTok{row,}
      \AttributeTok{layout.pos.col =}\NormalTok{ matchidx}\SpecialCharTok{$}\NormalTok{col}
\NormalTok{    ))}
\NormalTok{  \}}
\NormalTok{\}}

\FunctionTok{multiplot}\NormalTok{(p1,p2, p3, p4, p5, }\AttributeTok{cols =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/unnamed-chunk-23-1.pdf}}

The XGBoost model demonstrates strong predictive performance, with
predicted values closely tracking observed temperatures across the test
period. Residuals are centered around zero with no visible temporal
patterns, and the ACF shows no meaningful autocorrelation, indicating
well-behaved errors. The predicted-versus-observed scatterplot aligns
tightly around the 45-degree line, and the residual distribution is
approximately normal with small variance. Overall, the diagnostics
suggest that XGBoost effectively captures the nonlinear and seasonal
structure of the temperature series and produces accurate, unbiased
predictions.

\subsubsection{Forecasting and
Interpretation}\label{forecasting-and-interpretation-1}

Future meteorological covariates were constructed by cycling the most
recent 365-day pattern, enabling the model to simulate realistic
seasonal dynamics.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat\_state }\OtherTok{\textless{}{-}}\NormalTok{ dat }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{date =} \FunctionTok{as.Date}\NormalTok{(date)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(date) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{tmmx =} \FunctionTok{mean}\NormalTok{(tmmx, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{tmmn =} \FunctionTok{mean}\NormalTok{(tmmn, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{sph  =} \FunctionTok{mean}\NormalTok{(sph,  }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{vpd  =} \FunctionTok{mean}\NormalTok{(vpd,  }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{pr   =} \FunctionTok{mean}\NormalTok{(pr,   }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{rmin =} \FunctionTok{mean}\NormalTok{(rmin, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{rmax =} \FunctionTok{mean}\NormalTok{(rmax, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{srad =} \FunctionTok{mean}\NormalTok{(srad, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{vs   =} \FunctionTok{mean}\NormalTok{(vs,   }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{th   =} \FunctionTok{mean}\NormalTok{(th,   }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ungroup}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(date)}

\NormalTok{last\_365\_block }\OtherTok{\textless{}{-}}\NormalTok{ dat\_state }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_tail}\NormalTok{(}\AttributeTok{n =} \DecValTok{365}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(tmmn, sph, vpd, pr, rmin, rmax, srad, vs, th)}


\NormalTok{h }\OtherTok{\textless{}{-}} \DecValTok{730}   
\NormalTok{future\_list }\OtherTok{\textless{}{-}} \FunctionTok{vector}\NormalTok{(}\StringTok{"list"}\NormalTok{, }\AttributeTok{length =}\NormalTok{ h)}

\NormalTok{state }\OtherTok{\textless{}{-}}\NormalTok{ dat\_ml }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(date) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_tail}\NormalTok{(}\AttributeTok{n =} \DecValTok{7}\NormalTok{)}

\NormalTok{last\_date }\OtherTok{\textless{}{-}} \FunctionTok{max}\NormalTok{(state}\SpecialCharTok{$}\NormalTok{date)}

\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \FunctionTok{seq\_len}\NormalTok{(h)) \{}

\NormalTok{  new\_date }\OtherTok{\textless{}{-}}\NormalTok{ last\_date }\SpecialCharTok{+}\NormalTok{ i}
\NormalTok{  idx }\OtherTok{\textless{}{-}}\NormalTok{ ((i }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\%} \DecValTok{365}\NormalTok{) }\SpecialCharTok{+} \DecValTok{1}
\NormalTok{  exo\_today }\OtherTok{\textless{}{-}}\NormalTok{ last\_365\_block[idx, ]}

 
\NormalTok{  tmp }\OtherTok{\textless{}{-}}\NormalTok{ tibble}\SpecialCharTok{::}\FunctionTok{tibble}\NormalTok{(}
    \AttributeTok{date =}\NormalTok{ new\_date,}
    \AttributeTok{tmmn =}\NormalTok{ exo\_today}\SpecialCharTok{$}\NormalTok{tmmn,}
    \AttributeTok{sph  =}\NormalTok{ exo\_today}\SpecialCharTok{$}\NormalTok{sph,}
    \AttributeTok{vpd  =}\NormalTok{ exo\_today}\SpecialCharTok{$}\NormalTok{vpd,}
    \AttributeTok{pr   =}\NormalTok{ exo\_today}\SpecialCharTok{$}\NormalTok{pr,}
    \AttributeTok{rmin =}\NormalTok{ exo\_today}\SpecialCharTok{$}\NormalTok{rmin,}
    \AttributeTok{rmax =}\NormalTok{ exo\_today}\SpecialCharTok{$}\NormalTok{rmax,}
    \AttributeTok{srad =}\NormalTok{ exo\_today}\SpecialCharTok{$}\NormalTok{srad,}
    \AttributeTok{vs   =}\NormalTok{ exo\_today}\SpecialCharTok{$}\NormalTok{vs,}
    \AttributeTok{th   =}\NormalTok{ exo\_today}\SpecialCharTok{$}\NormalTok{th,}
    \AttributeTok{doy  =} \FunctionTok{yday}\NormalTok{(new\_date),}
    \AttributeTok{dow  =} \FunctionTok{wday}\NormalTok{(new\_date, }\AttributeTok{week\_start =} \DecValTok{1}\NormalTok{),}
    \AttributeTok{year =} \FunctionTok{year}\NormalTok{(new\_date)}
\NormalTok{  )}


\NormalTok{  tmp }\OtherTok{\textless{}{-}}\NormalTok{ tmp }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
      \AttributeTok{tmmx\_lag1  =}\NormalTok{ state}\SpecialCharTok{$}\NormalTok{tmmx[}\FunctionTok{nrow}\NormalTok{(state)],}
      \AttributeTok{tmmx\_lag2  =}\NormalTok{ state}\SpecialCharTok{$}\NormalTok{tmmx[}\FunctionTok{nrow}\NormalTok{(state) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{],}
      \AttributeTok{tmmx\_lag7  =}\NormalTok{ state}\SpecialCharTok{$}\NormalTok{tmmx[}\FunctionTok{nrow}\NormalTok{(state) }\SpecialCharTok{{-}} \DecValTok{6}\NormalTok{],}

      \AttributeTok{tmmn\_lag1  =}\NormalTok{ state}\SpecialCharTok{$}\NormalTok{tmmn[}\FunctionTok{nrow}\NormalTok{(state)],}
      \AttributeTok{sph\_lag1   =}\NormalTok{ state}\SpecialCharTok{$}\NormalTok{sph[}\FunctionTok{nrow}\NormalTok{(state)],}
      \AttributeTok{vpd\_lag1   =}\NormalTok{ state}\SpecialCharTok{$}\NormalTok{vpd[}\FunctionTok{nrow}\NormalTok{(state)],}
      \AttributeTok{pr\_lag1    =}\NormalTok{ state}\SpecialCharTok{$}\NormalTok{pr[}\FunctionTok{nrow}\NormalTok{(state)],}
      \AttributeTok{rmin\_lag1  =}\NormalTok{ state}\SpecialCharTok{$}\NormalTok{rmin[}\FunctionTok{nrow}\NormalTok{(state)],}
      \AttributeTok{rmax\_lag1  =}\NormalTok{ state}\SpecialCharTok{$}\NormalTok{rmax[}\FunctionTok{nrow}\NormalTok{(state)],}
      \AttributeTok{srad\_lag1  =}\NormalTok{ state}\SpecialCharTok{$}\NormalTok{srad[}\FunctionTok{nrow}\NormalTok{(state)],}
      \AttributeTok{vs\_lag1    =}\NormalTok{ state}\SpecialCharTok{$}\NormalTok{vs[}\FunctionTok{nrow}\NormalTok{(state)],}

  
      \AttributeTok{tmmx\_roll7 =} \FunctionTok{mean}\NormalTok{(state}\SpecialCharTok{$}\NormalTok{tmmx)}
\NormalTok{    )}

\NormalTok{  x\_new }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(tmp[, feature\_cols])}

\NormalTok{  pred\_new }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(xgb\_model, }\FunctionTok{xgb.DMatrix}\NormalTok{(x\_new))}

\NormalTok{  tmp}\SpecialCharTok{$}\NormalTok{tmmx }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(pred\_new)   }

\NormalTok{  future\_list[[i]] }\OtherTok{\textless{}{-}}\NormalTok{ tmp}

\NormalTok{  state }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{bind\_rows}\NormalTok{(state, tmp)}
\NormalTok{  state }\OtherTok{\textless{}{-}}\NormalTok{ state }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice\_tail}\NormalTok{(}\AttributeTok{n =} \DecValTok{7}\NormalTok{)}
\NormalTok{\}}

\NormalTok{future\_730 }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{bind\_rows}\NormalTok{(future\_list)}

\NormalTok{sd\_resid }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(test\_df}\SpecialCharTok{$}\NormalTok{resid)}

\NormalTok{future\_730 }\OtherTok{\textless{}{-}}\NormalTok{ future\_730 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{tmmx\_pred =}\NormalTok{ tmmx,}
    \AttributeTok{lower\_95  =}\NormalTok{ tmmx\_pred }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ sd\_resid,}
    \AttributeTok{upper\_95  =}\NormalTok{ tmmx\_pred }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ sd\_resid}
\NormalTok{  )}

\NormalTok{past\_all }\OtherTok{\textless{}{-}}\NormalTok{ dat\_state }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(date) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(date, tmmx) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{source =} \StringTok{"Observed (all history)"}\NormalTok{)}


\NormalTok{future\_plot }\OtherTok{\textless{}{-}}\NormalTok{ future\_730 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(date, tmmx\_pred, lower\_95, upper\_95) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{source =} \StringTok{"XGBoost forecast"}\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{data =}\NormalTok{ past\_all,}
            \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date, }\AttributeTok{y =}\NormalTok{ tmmx, }\AttributeTok{color =} \StringTok{"Observed"}\NormalTok{),}
            \AttributeTok{linewidth =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}

  \FunctionTok{geom\_ribbon}\NormalTok{(}\AttributeTok{data =}\NormalTok{ future\_plot,}
              \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date, }\AttributeTok{ymin =}\NormalTok{ lower\_95, }\AttributeTok{ymax =}\NormalTok{ upper\_95, }\AttributeTok{fill =} \StringTok{"95\% PI"}\NormalTok{),}
              \AttributeTok{alpha =} \FloatTok{0.2}\NormalTok{, }\AttributeTok{inherit.aes =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{data =}\NormalTok{ future\_plot,}
            \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date, }\AttributeTok{y =}\NormalTok{ tmmx\_pred, }\AttributeTok{color =} \StringTok{"Forecast"}\NormalTok{),}
            \AttributeTok{linewidth =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"XGBoost forecast of daily max temperature}\SpecialCharTok{\textbackslash{}n}\StringTok{(next 730 days with approximate 95\% prediction interval)"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Date"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Max temperature (tmmx, °C)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}
    \AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Observed"} \OtherTok{=} \StringTok{"black"}\NormalTok{, }\StringTok{"Forecast"} \OtherTok{=} \StringTok{"blue"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}
    \AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"95\% PI"} \OtherTok{=} \StringTok{"red"}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}
    \AttributeTok{legend.title  =} \FunctionTok{element\_blank}\NormalTok{(),}
    \AttributeTok{plot.title    =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Report_files/figure-latex/unnamed-chunk-24-1.pdf}}

This XGBoost model effectively captures nonlinear meteorological and
temporal dependencies, delivering strong short-term predictive accuracy
and stable long-horizon forecasts. The model serves as a complementary
alternative to ARIMAX, offering improved flexibility in handling lagged
covariates and complex interactions.

\subsection{Model Comparison}\label{model-comparison}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ar\_train }\OtherTok{\textless{}{-}}\NormalTok{ dat\_state\_lag }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(date }\SpecialCharTok{\textless{}=}\NormalTok{ split\_date)}
\NormalTok{ar\_test  }\OtherTok{\textless{}{-}}\NormalTok{ dat\_state\_lag }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(date }\SpecialCharTok{\textgreater{}}\NormalTok{  split\_date)}

\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(ar\_test) }\SpecialCharTok{==} \DecValTok{0} \SpecialCharTok{|} \FunctionTok{nrow}\NormalTok{(ar\_train) }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
  \FunctionTok{stop}\NormalTok{(}\StringTok{"ARIMAX train/test split produced empty set. Check date ranges of dat\_state\_lag vs dat\_ml."}\NormalTok{)}
\NormalTok{\}}

\NormalTok{start\_year }\OtherTok{\textless{}{-}} \FunctionTok{year}\NormalTok{(}\FunctionTok{min}\NormalTok{(ar\_train}\SpecialCharTok{$}\NormalTok{date))}
\NormalTok{start\_doy  }\OtherTok{\textless{}{-}} \FunctionTok{yday}\NormalTok{(}\FunctionTok{min}\NormalTok{(ar\_train}\SpecialCharTok{$}\NormalTok{date))}

\NormalTok{tmmx\_ts\_train }\OtherTok{\textless{}{-}} \FunctionTok{ts}\NormalTok{(}
\NormalTok{  ar\_train}\SpecialCharTok{$}\NormalTok{tmmx,}
  \AttributeTok{start     =} \FunctionTok{c}\NormalTok{(start\_year, start\_doy),}
  \AttributeTok{frequency =} \DecValTok{365}
\NormalTok{)}

\NormalTok{K }\OtherTok{\textless{}{-}} \DecValTok{3}

\NormalTok{fourier\_train }\OtherTok{\textless{}{-}} \FunctionTok{fourier}\NormalTok{(tmmx\_ts\_train, }\AttributeTok{K =}\NormalTok{ K)}

\NormalTok{xreg\_train }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}
\NormalTok{  fourier\_train,}
  \AttributeTok{sph\_lag1  =}\NormalTok{ ar\_train}\SpecialCharTok{$}\NormalTok{sph\_lag1,}
  \AttributeTok{vpd\_lag1  =}\NormalTok{ ar\_train}\SpecialCharTok{$}\NormalTok{vpd\_lag1,}
  \AttributeTok{srad\_lag1 =}\NormalTok{ ar\_train}\SpecialCharTok{$}\NormalTok{srad\_lag1,}
  \AttributeTok{vs\_lag1   =}\NormalTok{ ar\_train}\SpecialCharTok{$}\NormalTok{vs\_lag1}
\NormalTok{)}

\NormalTok{fit\_arimax\_cv }\OtherTok{\textless{}{-}} \FunctionTok{auto.arima}\NormalTok{(}
\NormalTok{  tmmx\_ts\_train,}
  \AttributeTok{xreg     =}\NormalTok{ xreg\_train,}
  \AttributeTok{seasonal =} \ConstantTok{FALSE}
\NormalTok{)}


\NormalTok{h\_test }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(ar\_test)}

\NormalTok{fourier\_test }\OtherTok{\textless{}{-}} \FunctionTok{fourier}\NormalTok{(tmmx\_ts\_train, }\AttributeTok{K =}\NormalTok{ K, }\AttributeTok{h =}\NormalTok{ h\_test)}

\NormalTok{xreg\_test }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}
\NormalTok{  fourier\_test,}
  \AttributeTok{sph\_lag1  =}\NormalTok{ ar\_test}\SpecialCharTok{$}\NormalTok{sph\_lag1,}
  \AttributeTok{vpd\_lag1  =}\NormalTok{ ar\_test}\SpecialCharTok{$}\NormalTok{vpd\_lag1,}
  \AttributeTok{srad\_lag1 =}\NormalTok{ ar\_test}\SpecialCharTok{$}\NormalTok{srad\_lag1,}
  \AttributeTok{vs\_lag1   =}\NormalTok{ ar\_test}\SpecialCharTok{$}\NormalTok{vs\_lag1}
\NormalTok{)}

\NormalTok{fc\_test }\OtherTok{\textless{}{-}} \FunctionTok{forecast}\NormalTok{(}
\NormalTok{  fit\_arimax\_cv,}
  \AttributeTok{xreg =}\NormalTok{ xreg\_test,}
  \AttributeTok{h    =}\NormalTok{ h\_test}
\NormalTok{)}

\NormalTok{ar\_test }\OtherTok{\textless{}{-}}\NormalTok{ ar\_test }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{arimax\_pred =} \FunctionTok{as.numeric}\NormalTok{(fc\_test}\SpecialCharTok{$}\NormalTok{mean))}

\NormalTok{compare\_df }\OtherTok{\textless{}{-}}\NormalTok{ test\_df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(date, tmmx, }\AttributeTok{xgb\_pred =}\NormalTok{ pred) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{inner\_join}\NormalTok{(ar\_test }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(date, arimax\_pred),}
             \AttributeTok{by =} \StringTok{"date"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(date)}

\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(compare\_df) }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
  \FunctionTok{stop}\NormalTok{(}\StringTok{"No overlapping dates between XGBoost test\_df and ARIMAX test set. Check date alignment."}\NormalTok{)}
\NormalTok{\}}

\NormalTok{calc\_metrics }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(obs, pred) \{}
\NormalTok{  rmse }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{((pred }\SpecialCharTok{{-}}\NormalTok{ obs)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\NormalTok{  mae  }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}\FunctionTok{abs}\NormalTok{(pred }\SpecialCharTok{{-}}\NormalTok{ obs))}
\NormalTok{  mape }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(}\FunctionTok{abs}\NormalTok{((pred }\SpecialCharTok{{-}}\NormalTok{ obs) }\SpecialCharTok{/}\NormalTok{ obs)) }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{  ss\_res }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{((obs }\SpecialCharTok{{-}}\NormalTok{ pred)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{  ss\_tot }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{((obs }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(obs))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{  r2 }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ ss\_res }\SpecialCharTok{/}\NormalTok{ ss\_tot}
  \FunctionTok{c}\NormalTok{(}\AttributeTok{RMSE =}\NormalTok{ rmse, }\AttributeTok{MAE =}\NormalTok{ mae, }\AttributeTok{MAPE =}\NormalTok{ mape, }\AttributeTok{R2 =}\NormalTok{ r2)}
\NormalTok{\}}

\NormalTok{m\_arimax }\OtherTok{\textless{}{-}} \FunctionTok{calc\_metrics}\NormalTok{(compare\_df}\SpecialCharTok{$}\NormalTok{tmmx, compare\_df}\SpecialCharTok{$}\NormalTok{arimax\_pred)}
\NormalTok{m\_xgb    }\OtherTok{\textless{}{-}} \FunctionTok{calc\_metrics}\NormalTok{(compare\_df}\SpecialCharTok{$}\NormalTok{tmmx, compare\_df}\SpecialCharTok{$}\NormalTok{xgb\_pred)}

\NormalTok{model\_compare }\OtherTok{\textless{}{-}}\NormalTok{ tibble}\SpecialCharTok{::}\FunctionTok{tibble}\NormalTok{(}
  \AttributeTok{Model =} \FunctionTok{c}\NormalTok{(}\StringTok{"ARIMAX + Fourier"}\NormalTok{, }\StringTok{"XGBoost"}\NormalTok{),}
  \AttributeTok{RMSE  =} \FunctionTok{c}\NormalTok{(m\_arimax[}\StringTok{"RMSE"}\NormalTok{], m\_xgb[}\StringTok{"RMSE"}\NormalTok{]),}
  \AttributeTok{MAE   =} \FunctionTok{c}\NormalTok{(m\_arimax[}\StringTok{"MAE"}\NormalTok{],  m\_xgb[}\StringTok{"MAE"}\NormalTok{]),}
  \AttributeTok{MAPE  =} \FunctionTok{c}\NormalTok{(m\_arimax[}\StringTok{"MAPE"}\NormalTok{], m\_xgb[}\StringTok{"MAPE"}\NormalTok{]),}
  \AttributeTok{R2    =} \FunctionTok{c}\NormalTok{(m\_arimax[}\StringTok{"R2"}\NormalTok{],   m\_xgb[}\StringTok{"R2"}\NormalTok{])}
\NormalTok{)}

\FunctionTok{kable}\NormalTok{(model\_compare, }\AttributeTok{digits =} \DecValTok{3}\NormalTok{,}
      \AttributeTok{caption =} \StringTok{"Performance comparison of ARIMAX + Fourier vs XGBoost on the same test dates"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrr@{}}
\caption{Performance comparison of ARIMAX + Fourier vs XGBoost on the
same test dates}\tabularnewline
\toprule\noalign{}
Model & RMSE & MAE & MAPE & R2 \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Model & RMSE & MAE & MAPE & R2 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
ARIMAX + Fourier & 8.593 & 7.608 & 1151.313 & 0.291 \\
XGBoost & 0.574 & 0.435 & 112.168 & 0.997 \\
\end{longtable}

The test-set results show that XGBoost substantially outperforms the
ARIMAX + Fourier model across all metrics, with far lower RMSE (0.57
vs.~8.59), MAE (0.43 vs.~7.61), and MAPE (112\% vs.~1151\%), as well as
a much higher R² (0.997 vs.~0.291). These differences are consistent
with the theoretical design of the two models. The ARIMAX + Fourier
approach relies on linear relationships, predefined seasonal components,
and a limited set of lagged regressors; as a result, it struggles to
capture nonlinear temperature dynamics and complex interactions among
meteorological variables. In contrast, XGBoost is a gradient-boosted
ensemble model capable of learning highly flexible, nonlinear
relationships and automatically capturing interactions among features,
including multiple lags, rolling averages, and time-of-year effects.
This flexibility allows it to model temperature patterns far more
accurately. However, ARIMAX has advantages in interpretability and
classical time-series structure, while XGBoost, despite its higher
accuracy, behaves more like a black box and requires more computational
resources. Overall, the comparison suggests that XGBoost is markedly
better suited for predictive performance in this dataset, especially
when nonlinear and interaction effects are important.

\section{\texorpdfstring{\textbf{Discussion}}{Discussion}}\label{discussion}

\subsection{Discussion}\label{discussion-1}

This unsupervised analysis shows that New York counties naturally group
into two interpretable climate types based on long-term averages of
temperature, humidity, precipitation, solar radiation, and wind speed.
One cluster corresponds to warmer, sunnier and relatively drier
counties, while the other represents cooler, more humid counties with
lower solar radiation. The same pattern appears in the summaries, the
PCA plot, and the map, and matches the expected coastal--inland contrast
(downstate/NYC and Long Island vs upstate interior), suggesting that the
clusters capture a real and useful climate gradient rather than a purely
algorithmic artifact.

The forecasting analysis evaluates two contrasting modeling strategies,
ARIMAX with Fourier terms and XGBoost, using statewide aggregated
meteorological time series. Because the forecasting models are trained
on the overall New York state average rather than cluster-specific
series, they do not incorporate spatial heterogeneity identified in the
clustering analysis. The ARIMAX model explicitly captures seasonality
and is highly interpretable, but it tends to smooth short-term
variability and struggles with nonlinear interactions among predictors.
In contrast, XGBoost is better able to learn nonlinear and lagged
relationships, producing higher predictive accuracy and more adaptive
short-term dynamics, though at the expense of interpretability.

\subsection{Limitations}\label{limitations}

This work has several limitations. Collapsing 2016--2020 daily data into
simple long-term means makes the clusters easy to interpret but discards
seasonality, year-to-year variability, and extreme events. The choice of
k = 2, while supported by diagnostics, is only one possible resolution
and yields unbalanced cluster sizes. Furthermore, the clustering is
purely unsupervised and does not incorporate socioeconomic or health
outcomes, so the resulting groups should be interpreted as descriptive
climate patterns rather than causal risk categories.

The forecasting models also have notable limitations. First, because
both ARIMAX and XGBoost were trained on statewide averages, they ignore
the meaningful spatial differences revealed by the clustering;
temperature dynamics may differ substantially across regions, and a
single aggregated model cannot capture these local variations. ARIMAX
may leave residual autocorrelation and fails to address nonlinear
temperature--meteorology interactions, while XGBoost relies heavily on
feature engineering and accumulates error during multi-step forecasting.
Neither approach explicitly incorporates long-term climate trends or
external drivers. Future extensions could include cluster-specific or
spatially varying models, hybrid approaches, or the integration of
broader climate indicators to improve robustness and capture regional
heterogeneity.

\section{\texorpdfstring{\textbf{Reference}}{Reference}}\label{reference}

Barnes, J., Sheffield, P., Graber, N., Jessel, S., Lanza, K., Limaye, V.
S., Morrow, F., Sauthoff, A., Schmeltz, M. and Smith, S. (2024) `Chapter
7: Human health and safety', in Stevens, A. (ed.) New York State Climate
Impacts Assessment{[}Interim version for public release{]}. Albany, NY:
New York State Energy Research and Development Authority.

Bazrafshan, O., Zamani, H., Farokhzadeh, B. and Caloiero, T. (2025) `A
spectral analysis-driven SARIMAX framework with Fourier terms for
monthly dust concentration forecasting', Earth, 6(4), 123.

Hyndman, R. J. and Athanasopoulos, G. (2018) Forecasting: Principles and
Practice, 2nd edn. Melbourne: OTexts. Available at:
\url{https://otexts.com/fpp2/} (Accessed 6 December 2025).

Lamie, C., Bader, D., Graziano, K., Horton, R., John, K., O'Hern, N. and
Spungin, S. (2024) `Chapter 2: New York State's changing climate', in
New York State Climate Impacts Assessment {[}Interim version for public
release{]}. Albany, NY: New York State Energy Research and Development
Authority.

Peel, M. C., Finlayson, B. L. and McMahon, T. A. (2007) `Updated world
map of the Köppen--Geiger climate classification', Hydrology and Earth
System Sciences, 11(5), pp.~1633--1644.

\end{document}
